### ISSUE TITLE
Add lint verifications on CI

### ISSUE THREAD

**Issue by seocam** [freeipa/ansible-freeipa#241] opened 2020-03-30 20:30 UTC
I would suggest that we use:

* [ ] black: code formatting
* [x] flake8: code style check
* [x] pydocstyle: enforce PEP 257 for docstrings
* [x] ansible-lint: ensure test and example playbooks and following Ansible standards
* [x] pylint: ensure python code quality
* [x] yamllint: lint for yaml files
* [x] flake8-bugbear: helps finding likely bugs and design problems.

We'd need a few tweaks to ensure they don't break Ansible standards. 

This would save us sometimes on reviewing thing that could automatically caught and also improve overall project quality.

**Comment by rjeffman** [comment] 2020-04-07 14:04
My 0.02 on pylint: I'm fine with it, I like it, but we should ensure a rate of 10.0.

For that, we might need to start with a configuration that leaves many checks out, so that current code passes, and enable the items one by one (maybe few by few), until we get everything we want enable. The problem is that some items will require a lot of work on several modules to be enabled.

(Supporting flake8 it is slightly different, and it seems PR #242 already covers it.)

**Comment by seocam** [comment] 2020-04-07 20:29
I've updated the #242 to cover pydocstyle and flake8. I'll probably open a different one for pylint and yet another for black, since those will probably yield a longer discussion.

**Comment by seocam** [comment] 2020-05-07 18:51
I've just added flake8-bugbear to the list (thanks for the suggestion @tiran).

**Comment by rjeffman** [comment] 2020-09-21 18:29
yamllint and ansible-lint are supported on CI, as Github actions, since #376 

The linters are also available through utils/lint-check.sh, and PR #393 is a proposal to get them available as pre-commit scripts.

**Comment by rjeffman** [comment] 2021-05-04 13:08
Pylint checks for modules is provided in PR #532. Roles are still not covered.

**Comment by rjeffman** [comment] 2021-07-10 02:44
Code formatting with `black` will not be adopted anytime soon.

Even though `pylint` is not yet enabled for roles, I'm closing this issue in favor of a new one, specific to add pylint to roles.

**Closed by rjeffman** 2021-07-10 02:44 UTC
