### ISSUE TITLE
Server installation test fails

### ISSUE THREAD

**Issue by unitynet-dk** [freeipa/ansible-freeipa#297] opened 2020-06-09 01:11 UTC
Hi developers
I can't really make the installation of the FreeIPA server work. An error persists during server installation testing:
"An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_server.__spec__ is None
fatal: [auth]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}"
I have tried installing under Ubuntu 16.04 and 18.04 as well as CentOS 7. They all fail in the same place.
Somewhere I read that the installation should work with python 2.7, but I can't make it work either.

Yours sincerely
Søren Sjøstrøm
Unitynet

**Comment by t-woerner** [comment] 2020-06-09 08:50
Which ansible and ansible-freeipa version do you have?

**Comment by unitynet-dk** [comment] 2020-06-09 09:03
Hi

Thanks for your reply.

I’m using Ansible version 2.9.2 and ansible-freeipa version 0.1.10 (the one from ansible-galaxy).

**Comment by t-woerner** [comment] 2020-06-09 09:28
Which operation system do you use on the controller? How have you installed ansible on the controller?

I am able to use the collection with ansible 2.9.6 on my Fedora-32 controller without issues to deploy CentOS-7 and RHEL-8 machines. I even tried different ways:

```
---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true

  roles:
  - role: freeipa.ansible_freeipa.ipaserver
    state: present
```

and

```
---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true

  collections:
  - freeipa.ansible_freeipa

  tasks:
  - name: Deploy server
    include_role:
      name: ipaserver
```

**Comment by t-woerner** [comment] 2020-06-09 09:54
Is ansible working for you if you add this? https://github.com/ansible/ansible/issues/68361#issuecomment-601740874

**Comment by unitynet-dk** [comment] 2020-06-09 10:12
I have now tried to upgrade Ansible to version 2.9.9 and now I get a new error message:

"freeipa version '4.3.1' is too old”

My controller is a Mac with macOS Catalina running Python 2.7.15

**Comment by t-woerner** [comment] 2020-06-09 10:25
There have been lots of fixes in ansible lately for collections.

You are using a freeipa version that is not usable by the ipaserver role. Is is possible for you to use a newer version? Please have a look at https://github.com/freeipa/ansible-freeipa/#supported-freeipa-versions
The management modules are only able to work with IPA 4.4 and up also.

**Comment by unitynet-dk** [comment] 2020-06-09 10:42
How do I get hold of IPA 4.4? Just tried to clone from git repository, but only version 4.3.1 is still installed.

**Comment by t-woerner** [comment] 2020-06-09 11:03
For the server you will need at least IPA 4.5. Which OS do you have on the server machine? With CentOS-7 you should get IPA 4.6.x for example.

**Comment by unitynet-dk** [comment] 2020-06-09 11:09
My server is running on Ubuntu 18.04. It is deployed via my MAAS server, so I can relatively quickly convert it to a CentOS 7 machine.
But where can I download FreeIPA later than version 4.3.1?

**Comment by t-woerner** [comment] 2020-06-09 11:24
According to https://packages.ubuntu.com/search?keywords=freeipa-server there should be 4.7.0 in bionic (18.04LTS). 4.3.1 is in xenial (16.04LTS).
I do not know if the IPA packages in Ubuntu are working properly though.

**Comment by rjeffman** [comment] 2020-06-09 11:45
@unitynet-dk, I strongly suggest that you follow the procedure to install Python 3 on macOS Catalina. Not only for Ansible usage, but for general use. It is recommended even by Apple when running python on the terminal.

**Comment by seocam** [comment] 2020-06-09 12:04
That's exactly the same issue I'm facing when trying to use ansible-freeipa from a galaxy installation.

Currently I'm going around it by cloning the repo, checking out the tag I need and setting the paths in ansible.cfg. 

My controller host is a Fedora `32` with ansible installed using pip (ansible version `2.9.9`). Ansible_freeipa version `0.1.10`.

**Comment by unitynet-dk** [comment] 2020-06-09 13:17
Hi Thomas

Forget my message that the freeipa version is too old. My mistake - I forgot that I downgraded my server to Ubuntu 16.04 late last night :-)

Now I'm back with a fresh install of Ubuntu 18.04. Also, I upgraded Python on my Mac to version 3.7.7.

When I run the installation downloaded via ansible-galaxy, I am left with the original error message:
"ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_server .__ spec__ is None"

If I run the installation downloaded via git clone, I get a new error message:
"ModuleNotFoundError: No module named ipapython"

**Comment by seocam** [comment] 2020-06-09 13:52
BTW this bug is a duplicate of https://github.com/freeipa/ansible-freeipa/issues/144

**Comment by seocam** [comment] 2020-06-09 13:55
@unitynet-dk thanks for opening this issue (it was good because it brought light to a serious problem again).
There is an ansible patch here that helps going around the issue: https://github.com/ansible/ansible/issues/68361

I'm closing this so we can converge discussions in the older issue. Please continue with your inputs in #144.

**Closed by seocam** 2020-06-09 13:55 UTC
