### ISSUE TITLE
Modules don't work with python 3.6

### ISSUE THREAD

**Issue by varadinov** [freeipa/ansible-freeipa#207] opened 2020-02-15 13:27 UTC
Ansible 2.9.5 with python 3.6.8 with ansible-freeipa 0.8.1-1
**ipaserver : Install - Server installation test** is failing with python 3.6.8 (check below). Everything is working with python 2.7.

TASK [ipaserver : Install - Server installation test] **********************************************************************************************************************************************************************************An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_server.__spec__ is None
fatal: [ipa01.infra.local]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

python 3.6 is also installed on the target IPA server

**Comment by t-woerner** [comment] 2020-02-17 11:26
Please run this in verbose mode "-vvv" and add the complete traceback here.

**Comment by varadinov** [comment] 2020-02-19 17:37
**The full traceback is:**
Traceback (most recent call last):
  File "/opt/ansible3/lib64/python3.6/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/opt/ansible3/lib64/python3.6/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/ansible3/lib64/python3.6/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/opt/ansible3/lib64/python3.6/site-packages/ansible/plugins/action/__init__.py", line 815, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/opt/ansible3/lib64/python3.6/site-packages/ansible/plugins/action/__init__.py", line 209, in _configure_module
    **become_kwargs)
  File "/opt/ansible3/lib64/python3.6/site-packages/ansible/executor/module_common.py", line 1258, in modify_module
    environment=environment)
  File "/opt/ansible3/lib64/python3.6/site-packages/ansible/executor/module_common.py", line 1095, in _find_module_utils
    py_module_cache, zf)
  File "/opt/ansible3/lib64/python3.6/site-packages/ansible/executor/module_common.py", line 731, in recursive_finder
    [os.path.join(*py_module_name[:-idx])])
  File "/opt/ansible3/lib64/python3.6/site-packages/ansible/executor/module_common.py", line 650, in __init__
    self.get_source()
  File "/opt/ansible3/lib64/python3.6/site-packages/ansible/executor/module_common.py", line 666, in get_source
    data = pkgutil.get_data(to_native(self._package_name), to_native(self._mod_name + '.py'))
  File "/usr/lib64/python3.6/pkgutil.py", line 616, in get_data
    spec = importlib.util.find_spec(package)
  File "/usr/lib64/python3.6/importlib/util.py", line 102, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_server.__spec__ is None
fatal: [ipa01.infra.local]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

**ping from server**
  "ansible_facts": {
        **"discovered_interpreter_python": "/usr/bin/python"**
    },
    "changed": false,
    "ping": "pong"

It discovers python2 as interpreter. Python3 is also available...

**Comment by lnxart** [comment] 2020-02-19 20:03
We faced the same issue with module "ipagroup":

$ ansible-playbook --version
ansible-playbook 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/server/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]


The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/action/__init__.py", line 803, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/action/__init__.py", line 197, in _configure_module
    **become_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/module_common.py", line 1258, in modify_module
    environment=environment)
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/module_common.py", line 1095, in _find_module_utils
    py_module_cache, zf)
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/module_common.py", line 731, in recursive_finder
    [os.path.join(*py_module_name[:-idx])])
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/module_common.py", line 650, in __init__
    self.get_source()
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/module_common.py", line 666, in get_source
    data = pkgutil.get_data(to_native(self._package_name), to_native(self._mod_name + '.py'))
  File "/usr/lib/python3.6/pkgutil.py", line 616, in get_data
    spec = importlib.util.find_spec(package)
  File "/usr/lib/python3.6/importlib/util.py", line 102, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_freeipa_module.__spec__ is None

fatal: [ipaserver.example.com]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

**Comment by tsabirgaliev** [comment] 2020-02-24 09:00
same error with Python 3.7 on Macos

```ansible-playbook --version
ansible-playbook 2.9.2
  config file = /Users/tair/.../ansible.cfg
  configured module search path = ['/Users/tair/.ansible/plugins/modules', '/opt/local/share/ansible/plugins/modules']
  ansible python module location = /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ansible
  executable location = /opt/local/bin/ansible-playbook
  python version = 3.7.6 (default, Dec 22 2019, 01:09:06) [Clang 11.0.0 (clang-1100.0.33.12)]```

**Comment by t-woerner** [comment] 2020-02-24 10:15
Is /usr/bin/python the proper python3.6 binary? Since Python 3.4 the module loaders are only returning specs and not te loaders anymore. Therefore I think you are using a mixture of different python versions.

**Comment by Papy-Bretzel** [comment] 2020-02-25 08:59
Hey there.
I'm actually using the freeipa collection 0.8.1 on a Ubuntu 18.04 server which uses by default python 2.7.17. I have no problem on this machine.
But on my laptop, with the same playbook and inventory, I encounter the exact same error, at the exact same step of the install using python 3.8 : 
> ValueError:  ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_freeipa_module.\_\_spec\_\_ is None

I tried to specify path to python 2.7.17 via the `INTERPRETER_PHYTON` config var, but without any success  
Both uses Ansible 2.9.4. The full trace log is identical to the one posted by varadinov and lnxart.

**Comment by t-woerner** [comment] 2020-03-02 08:31
@Papy-Bretzel Do you have python2 and python3 on the server and notebook? Which python version do you have on the node and the controller?

Ansible has a mapping of python interpreters per distro. By default it uses /usr/bin/python3 according to INTERPRETER_PYTHON_DISTRO_MAP since Ubuntu 16 in ansible/config/base.yml.

**Comment by t-woerner** [comment] 2020-03-02 08:34
@varadinov You are writing that "It discovers python2 as interpreter", but you are using `/opt/ansible3/lib64/python3.6/`. You are using Python2 binary and Python3 bindings somehow, this is the issue.

**Comment by tsabirgaliev** [comment] 2020-03-02 18:39
@t-woerner in my case this happens with python 3.7 on control node (Macos) and a clean Centos 8 virtual machine as a managed node with only virtualbox guest additions installed (a vagrant vm).

Workaround: downgraded to python 2.7 on control node

**Comment by rafasgj** [comment] 2020-03-02 22:47
I tried with both the current master tree (commit 200eb30) and with release 0.1.8, using macOS 10.15.3, and vagrant CentOS 8 vm, and install-server.yml worked fine.

Some useful information: ansible --version I have ansible 2.9.5, ansible python module location = /Users/rafael/Library/Python/3.7/lib/python/site-packages/ansible, executable location = /Users/rafael/Library/Python/3.7/bin/ansible and python version = 3.7.3 (default, Dec 13 2019, 19:58:14) [Clang 11.0.0 (clang-1100.0.33.17)].

**Comment by skept1c** [comment] 2020-03-03 08:38
almost same problem in my case:
control node: centos 7, ansible 2.9.5, python 3.6.8
target node: centos 8, python 3.6.8

`pip3 install ansible==2.8.8` on control node did the trick for me, so there is definetely a bug in ansible 2.9.x when it uses python 3.6

**Comment by Papy-Bretzel** [comment] 2020-03-03 09:27
@t-woerner I'm using ansible in a vagrant environment. I deploy freeipa on a Vagrant VM, so the managed node is exactly the same. The vagrant box used is [geerlingguy/centos7](https://app.vagrantup.com/geerlingguy/boxes/centos7).
My controllers are either the server I talked to you about, using python 2.7.17  without any problem :
```
cruiz@srv-lab-1:~$ ansible --version
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cruiz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```
... or a laptop running Manjaro Linux, and using by default python 3.8, which fails.

Reinstalling ansible using pip3 on the working server makes it fail with the same tracelog :
```
cruiz@srv-lab-1:~/memoire-2020/lab$ sudo -H pip3 install ansible
[...]
cruiz@srv-lab-1:~/memoire-2020/lab$ ansible-playbook -i inventory.ini freeipa.yml
[...]
TASK [ipaserver : Install - Server installation test] *************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_server.__spec__ is None
fatal: [freeipa]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

cruiz@srv-lab-1:~/memoire-2020/lab$ ansible --version
ansible 2.9.4
  config file = /home/cruiz/memoire-2020/lab/ansible.cfg
  configured module search path = ['/home/cruiz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```
The problem obviously comes from the combo python 3.6 (or later) + ansible 2.9, as pointed out @skept1c, as downgrading python or ansible solve the problem

**Comment by t-woerner** [comment] 2020-03-03 09:46
For Python2 Ansible you should use pip2, not pip3.

**Comment by Papy-Bretzel** [comment] 2020-03-03 09:58
Using `pip3` created the bug, reinstalling ansible through `apt` (= installing python 2 ansible) on the control node solves the problem for me.

The freeipa module fails when all of these conditions are met :
* Ansible uses Python 3
* Python version > 3.6
* Ansible version > 2.9

**Comment by rjeffman** [comment] 2020-03-03 14:28
As I had a macOS box (10.15.3) available, I tried a setup similar to @tsabirgaliev, as ended up with Ansible 2.9.5, and Python 3.7.3, tested both latest master branch and tag v0.1.8 against a Vagrant Centos8 VM node. Everything worked fine.

Under macOS, I had to add $HOME/Library/Python/3.7/bin to the path, as pip doesn't do it, and ran pip as `python3 -m pip` (as I always do, so I don't mix versions, as 'pip' might be different versions depending on the OS and configuration). VM used was `centos/8`.

**Comment by Thulium-Drake** [comment] 2020-08-12 12:37
Using the following:

- Ansible 2.9.10
- Python 3.7.3
- Ansible-FreeIPA 0.1.12

Still breaks with the following stacktrace:
```
TASK [freeipa.ansible_freeipa.ipaserver : Install - Server installation test] ****************************************
task path: /root/projects/htm/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipaserver/tasks/install.yml:46
<ipa1.deploy.lab> ESTABLISH SSH CONNECTION FOR USER: ansible
<ipa1.deploy.lab> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/8171f5707c ipa1.deploy.lab '/bin/sh -c '"'"'echo ~ansible && sleep 0'"'"''
<ipa1.deploy.lab> (0, b'/home/ansible\n', b'')
<ipa1.deploy.lab> ESTABLISH SSH CONNECTION FOR USER: ansible
<ipa1.deploy.lab> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/8171f5707c ipa1.deploy.lab '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp `"&& mkdir /home/ansible/.ansible/tmp/ansible-tmp-1597235383.0348544-1807-183881857231794 && echo ansible-tmp-1597235383.0348544-1807-183881857231794="` echo /home/ansible/.ansible/tmp/ansible-tmp-1597235383.0348544-1807-183881857231794 `" ) && sleep 0'"'"''
<ipa1.deploy.lab> (0, b'ansible-tmp-1597235383.0348544-1807-183881857231794=/home/ansible/.ansible/tmp/ansible-tmp-1597235383.0348544-1807-183881857231794\n', b'')
<ipa1.deploy.lab> ESTABLISH SSH CONNECTION FOR USER: ansible
<ipa1.deploy.lab> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/8171f5707c ipa1.deploy.lab '/bin/sh -c '"'"'rm -f -r /home/ansible/.ansible/tmp/ansible-tmp-1597235383.0348544-1807-183881857231794/ > /dev/null 2>&1 && sleep 0'"'"''
<ipa1.deploy.lab> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/opt/ansible/2.9.10/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/opt/ansible/2.9.10/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 654, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/ansible/2.9.10/lib/python3.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/opt/ansible/2.9.10/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 831, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/opt/ansible/2.9.10/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 215, in _configure_module
    **become_kwargs)
  File "/opt/ansible/2.9.10/lib/python3.7/site-packages/ansible/executor/module_common.py", line 1252, in modify_module
    environment=environment)
  File "/opt/ansible/2.9.10/lib/python3.7/site-packages/ansible/executor/module_common.py", line 1089, in _find_module_utils
    py_module_cache, zf)
  File "/opt/ansible/2.9.10/lib/python3.7/site-packages/ansible/executor/module_common.py", line 725, in recursive_finder
    [os.path.join(*py_module_name[:-idx])])
  File "/opt/ansible/2.9.10/lib/python3.7/site-packages/ansible/executor/module_common.py", line 644, in __init__
    self.get_source()
  File "/opt/ansible/2.9.10/lib/python3.7/site-packages/ansible/executor/module_common.py", line 660, in get_source
    data = pkgutil.get_data(to_native(self._package_name), to_native(self._mod_name + '.py'))
  File "/usr/lib/python3.7/pkgutil.py", line 619, in get_data
    spec = importlib.util.find_spec(package)
  File "/opt/ansible/2.9.10/lib/python3.7/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_server.__spec__ is None
fatal: [ipa1.deploy.lab]: FAILED! => 
  msg: Unexpected failure during module execution.
  stdout: ''
```

Running the same version of Ansible and Ansible-FreeIPA on Python 2.7.16 works fine, but as Python complains, is slowly turning into a security nightmare.

Hope this helps :-) happy to test if needed!

**Comment by Thulium-Drake** [comment] 2020-08-12 14:06
Seems related to #315

I think this one can be closed as a duplicate

**Comment by Thulium-Drake** [comment] 2020-08-12 14:39
Just tried it with the following Ansible version:

```
$ ansible --version
ansible 2.10.0rc4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/2.10.0a8/lib/python3.7/site-packages/ansible
  executable location = /opt/ansible/2.10.0a8/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

Works like a charm!

**Comment by t-woerner** [comment] 2020-09-03 12:04
Closing as duplicate of #315

**Closed by t-woerner** 2020-09-03 12:04 UTC
