### ISSUE TITLE
ipadnsforwardzones - dictionary requested, could not parse JSON or key=value

### ISSUE THREAD

**Issue by t-readyroc** [freeipa/ansible-freeipa#446] opened 2020-11-19 00:23 UTC
Task:

```    - name: create forwarding zones
      ipadnsforwardzone:
        ipaadmin_password: "{{ ipa_admin_password }}"
        state: present
        name: example.com
        forwarders:
          - 10.200.138.11
          - 10.200.138.12
        forwardpolicy: first
```
Result:

`FAILED! => {"changed": false, "msg": "Failure when processing no_log parameters. Module invocation will be hidden. dictionary requested, could not parse JSON or key=value"}`

Not sure where I'm going wrong, as my task looks identical to [the documentation](https://github.com/freeipa/ansible-freeipa/blob/master/README-dnsforwardzone.md).

**Comment by rjeffman** [comment] 2020-11-19 11:42
As per the error shown, there is a failure processing the no_log parameters, and, in your code, the only no_log parameter is ipaadmin_password. I'd check the value of `ipa_admin_password`.

**Comment by t-readyroc** [comment] 2020-11-19 13:56
@rjeffman appreciate the reply. This var is used in all of our other playbooks, but just to be sure, I included the following task, before the ipadnsforwardzone task:

```
    - debug:
        msg: "The ipa_admin_passowrd is {{ ipa_admin_password }}"
```

Which (correctly) resulted in the following output:

```
TASK [debug] ***************************************************
ok: [gr-ipaprd01.domain] => {
    "msg": "The ipa_admin_passowrd is <correct_password>"
}
```
Still got the same output of the above ipadnsforwardzone task after the debug task ran.

**Comment by t-readyroc** [comment] 2020-11-19 14:05
For clarity, all in one. Here's the entire playbook (secrets file is the encrypted password):

```
- name: Playbook to create DNS forwarding zones in IPA
  hosts: ipaserver
  remote_user: admin
  become: yes
  vars_files:
    - vars/global_ipa_secrets.yml

  tasks:
    - debug:
        msg: "The ipa_admin_passowrd is {{ ipa_admin_password }}"

    - name: create forwarding zones
      ipadnsforwardzone:
        ipaadmin_password: "{{ ipa_admin_password }}"
        state: present
        name: example.com
        forwarders:
          - 10.200.138.11
          - 10.200.138.12
        forwardpolicy: first
```

Which produces the following output:

```
PLAY [Playbook to create DNS forwarding zones in IPA] ********************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
ok: [gr-ipaprd01.domain]

TASK [debug] *************************************************************************************************************************************************************************
ok: [gr-ipaprd01.domain] => {
    "msg": "The ipa_admin_passowrd is <correct_password>"
}

TASK [create forwarding zones] ***************************************************************************************************************************************************************************
fatal: [gr-ipaprd01.domain]: FAILED! => {"changed": false, "msg": "Failure when processing no_log parameters. Module invocation will be hidden. dictionary requested, could not parse JSON or key=value"}

PLAY RECAP ***************************************************************************************************************************************************************************
gr-ipaprd01.domain : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

**Comment by rjeffman** [comment] 2020-11-19 15:14
The problem is that the forwarders is not a list of values, but a list of dictionaries.

To fix it, change the `forwarders` to:
```
forwarders:
  - ip_address: 10.200.138.11
  - ip_address: 10.200.138.12
```

I'm marking this issue as a bug. Either the module needs to be fixed, or the documentation.

Thank you for raising this issue.

**Comment by t-readyroc** [comment] 2020-11-20 01:09
Awesome! Thanks for looking into it.

**Comment by rjeffman** [comment] 2020-11-25 22:40
ansible-freeipa 0.3.0 has been released and has a fix for this issue.

If it does not work for you, please reopen this issue and let us know.

**Closed by rjeffman** 2020-11-25 22:40 UTC
Labels: pr-avaiable
