### ISSUE TITLE
Error creating nonposix group

### ISSUE THREAD

**Issue by Yalafeg** [freeipa/ansible-freeipa#528] opened 2021-04-12 15:48 UTC
Hello,

We are trying to create non posix group using the latest version of modules.

Kindly find below the error that appears when trying to create the group
fatal: [xxxxx]: FAILED! => {"changed": false, "msg": "group_mod: xxxx : Unknown option: nonposix"}

The task is written as below:
- name: Create group xxxx
  ipagroup:
    ipaadmin_password: *************
    name: xxxxx
    nonposix: true

Please advise.

Best regards,

**Comment by Yalafeg** [comment] 2021-04-13 10:32
Hello,

The ipa version:

VERSION: 4.5.4, API_VERSION: 2.228

Regarding the group creation, if the group does not exist, we are able to create it without errors.

But, if the group is already created (as a non-posix group), and we are trying to modify the group attributes (ex: adding new groups, etc..) while keeping the variable nonposix to true, we are getting the same error.
In other terms, if the group is created we should remove the nonposix attribute, otherwise we are getting the same error.

Thank you,

**Comment by rjeffman** [comment] 2021-04-13 11:22
Yesterday, I tested with IPA 4.6+. I'll check it again, against older versions, but I might not have enough time in the next days, so, I'm marking this as a `bug` so we don't forget to look at it later. It looks like an idempotence issue to me.

As a (poor) workaround, please, use `nonposix: true` only when creating the group.

**Comment by Yalafeg** [comment] 2021-04-14 13:00
Thank you for your reply. I tried to reproduce the issue with the below version and faced the same problem.
VERSION: 4.8.7, API_VERSION: 2.239

Thank you for the workaround, will be using it for the moment.

**Comment by chr15p** [comment] 2021-04-29 16:37
I can reproduce this with IPA 4.8.0 by using an old version of ansible-freeipa.   The original group module sent "nonposix" as an argument to the group_mod call, which gives you that error message. The latest (oct 2020) version of ipagroup.py sends the correct "posix" option instead. 

I haven't figured out exactly when the fix happened but can you update ansible-freeipa to the latest release and give it another try?

**Comment by rjeffman** [comment] 2021-04-29 16:57
@chr15p the issue depends on the current state of the group and the playbook being executed. There are other wrong behaviors, like not changing status or changing when it shouldn't, and that´s why I´m thinking about an idempotence issue here.

Unfortunately, this issue is not yet fixed.

**Closed** 2021-09-16 19:55 UTC
Labels: bug
