### ISSUE TITLE
[ipaserver] ansible_freeipa.plugins.module_utils.ansible_ipa_server.__spec__ is None

### ISSUE THREAD

**Issue by lucab85** [freeipa/ansible-freeipa#503] opened 2021-01-27 15:52 UTC
Hello, I'd like to report this result on my workstation.
### Expected
`ok`
### Result
```
TASK [freeipa.ansible_freeipa.ipaserver : Install - Server installation test] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_server.__spec__ is None
fatal: [ipa]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```
### Reproducer 
```
git clone https://github.com/lucab85/ansible-role-ipaserver
cd ansible-role-ipaserver
vagrand --provision up
```
### Environment
```
Fedora 33
ansible 2.9.16
Vagrant 2.2.9
Image: generic/rhel8:3.1.22
freeipa.ansible_freeipa:0.3.4
```

**Comment by rjeffman** [comment] 2021-01-27 19:57
There is a know issue with Ansible 2.9 series (ansible/ansible#68361). You might try to use with Ansible 2.8 or 2.10.

I'm closing this as a duplicate of #315, where this discussion is currently being held.

**Closed by rjeffman** 2021-01-27 19:57 UTC
Labels: duplicate
