### ISSUE TITLE
ipaclient: Install - IPA client test - Unexpected failure during module execution.

### ISSUE THREAD

**Issue by SrCaio** [freeipa/ansible-freeipa#144] opened 2019-11-08 16:35 UTC
When i import the role ipaclient the module ansible_ipa_client throw this error:

`Traceback (most recent call last):
  File "/usr/src/ansible/lib/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/src/ansible/lib/ansible/executor/task_executor.py", line 650, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/src/ansible/lib/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/src/ansible/lib/ansible/plugins/action/__init__.py", line 796, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/src/ansible/lib/ansible/plugins/action/__init__.py", line 181, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, self._templar,
  File "/usr/src/ansible/lib/ansible/executor/module_common.py", line 1255, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, templar, module_compression,
  File "/usr/src/ansible/lib/ansible/executor/module_common.py", line 1094, in _find_module_utils
    recursive_finder(module_name, remote_module_fqn, b_module_data, py_module_names,
  File "/usr/src/ansible/lib/ansible/executor/module_common.py", line 730, in recursive_finder
    module_info = CollectionModuleInfo(py_module_name[-idx],
  File "/usr/src/ansible/lib/ansible/executor/module_common.py", line 650, in __init__
    self.get_source()
  File "/usr/src/ansible/lib/ansible/executor/module_common.py", line 666, in get_source
    data = pkgutil.get_data(to_native(self._package_name), to_native(self._mod_name + '.py'))
  File "/usr/local/lib/python3.8/pkgutil.py", line 619, in get_data
    spec = importlib.util.find_spec(package)
  File "/usr/local/lib/python3.8/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_client.__spec__ is None`

Can someone help me and tell me what I'm wrong?

**Comment by t-woerner** [comment] 2019-11-08 17:11
How have you downloaded ansible-freeipa? Which ansible version are you using?

**Comment by SrCaio** [comment] 2019-11-08 18:25
I have download ansible-freeipa collection from ansible galaxy ( ansible-galaxy collection install freeipa.ansible_freeipa:0.1.6-3 -p mypath/ )

Ansible Version:  2.10.0.dev0
Python Version: 3.8.0, 3.7.3 and 3.7.1

**Comment by AleRousse** [comment] 2019-12-02 01:57
Got the same issue too. 
It's something about ansible not finding any path for the custom modules shipped with ansible-freeipa collections.

**Comment by AleRousse** [comment] 2019-12-02 03:08
I confirm that the issue is with module path in 2.9+ version of ansible.
Tested on 2.8 and it work fine. Looks like ansible bring  some breaking change in collection structure in 2.9+ version

**Comment by aneagoe** [comment] 2020-03-19 16:50
Additionally, this *does* work as long as one uses Python 2.7 and Ansible 2.9+. I will try to open an issue in ansible project and reference this one.

**Comment by t-woerner** [comment] 2020-07-07 14:51
Please have a look at https://github.com/freeipa/ansible-freeipa/issues/315
It provides some workarounds for this issue.

**Comment by t-woerner** [comment] 2020-09-03 12:04
Closing as duplicate of #315

**Closed by t-woerner** 2020-09-03 12:04 UTC
