### ISSUE TITLE
Requirements update

### ISSUE THREAD

**Issue by igramic** [freeipa/ansible-freeipa#436] opened 2020-11-11 10:05 UTC
While running today ipahost I was getting    
"msg": "No module named 'ipaserver'"

Can we add to requirements:

- python3-ipaserver

**Comment by rjeffman** [comment] 2020-11-13 19:47
The problem is that ansible-freeipa might not be installed along with ipaserver. It is meant to be used in an Ansible controller, and the IPA server usually is in a different node.

It seems the hostnode you are trying to manage does not have FreeIPA installed.

Log into the node you are trying to manage and check the result of `ipa --version`.

**Comment by igramic** [comment] 2020-11-16 08:23
System from where we run this is IPA client and it had valid enrollment.

# ipa --version
VERSION: 4.8.7, API_VERSION: 2.239

**Comment by rjeffman** [comment] 2020-11-16 11:47
@igramic, do the hosts, on your playbooks, target an IPA client or an IPA server?

**Comment by igramic** [comment] 2020-11-19 10:22
they target ipa client

**Comment by rjeffman** [comment] 2020-11-19 11:02
ansible-freeipa is meant to be used against the server, not the client. That is why you are seeing this error.

**Comment by rjeffman** [comment] 2022-01-21 18:15
Since PR #631 was merged it is possible to execute modules on the client hosts, therefore, I'm closing this issue.

If the resolution isn't sufficient, please, re-open the issue providing the details.

**Closed by rjeffman** 2022-01-21 18:15 UTC
