### ISSUE TITLE
IPA Replica Installation Fails

### ISSUE THREAD

**Issue by jasperroloff** [freeipa/ansible-freeipa#450] opened 2020-11-20 01:08 UTC
Hi,

I try to install a FreeIPA replica using the `ipareplica` ansible role, but it fails at the `Install - Replica installation test` task:

```
TASK [ipareplica : Install - Replica installation test] ************************************************************************************************
fatal: [hostname.example.org]: FAILED! => {"changed": false, "msg": "common_check() missing 2 required positional arguments: 'skip_mem_check' and 'setup_ca'"}
```

According to the error message, I guess this has to do with the `common_check` method:

https://github.com/freeipa/ansible-freeipa/blob/4ab38e8bc66f5b0b245ad9f52d4ffc81ef28487c/roles/ipareplica/library/ipareplica_test.py#L407

https://github.com/freeipa/freeipa/blob/d30939ebfdcd820c7e26c0709f48185cc88431fc/ipaserver/install/server/replicainstall.py#L572

Is there a workaround for this bug or did I miss something from the docs?

Thank you!

Versions used:
* Ansible: 2.8.12
* Python: 3.7.9
* ansible_freeipa collection: 0.2.1 (from galaxy)
* Local OS: macOS 11.0.1
* Remote OS: Fedora 33

**Comment by rjeffman** [comment] 2020-11-20 19:20
@jasperroloff did you use the example playbooks? Can you post the playbook you used to install the replica?

**Comment by jasperroloff** [comment] 2020-11-21 00:07
I just tested it with one of the example playbooks (and inventory) and the bug still occurs.

Playbook:
```
---
- name: Playbook to configure IPA replicas
  hosts: ipareplicas
  become: true
  collections:
    - freeipa.ansible_freeipa
  roles:
    - role: ipareplica
      state: present
```

Inventory:
```
[ipareplicas]
ipa-2.test.<domain> ansible_host=<IPv6>

[ipareplicas:vars]
ipaadmin_principal=admin
ipaadmin_password=XXXX
ipadm_password=XXXX
ipareplica_domain=test.<domain>
```

Ansible output:
```
~/ansible_freeipa_test » ansible-playbook -i inventory.ini playbook.yml                                                                                                          jasperroloff@Jaspers-MacBook-Pro

PLAY [Playbook to configure IPA replicas] ************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [ipa-2.test.<Domain>]

TASK [ipareplica : Import variables specific to distribution] ****************************************************************************************************************************************************
ok: [ipa-2.test.<Domain>] => (item=/Users/jasperroloff/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipareplica/vars/Fedora.yml)

TASK [ipareplica : Install IPA replica] **************************************************************************************************************************************************************************
included: /Users/jasperroloff/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipareplica/tasks/install.yml for ipa-2.test.<Domain>

TASK [ipareplica : Install - Ensure IPA replica packages are installed] ******************************************************************************************************************************************
ok: [ipa-2.test.<Domain>]

TASK [ipareplica : Install - Ensure IPA replica packages for dns are installed] **********************************************************************************************************************************
skipping: [ipa-2.test.<Domain>]

TASK [ipareplica : Install - Ensure IPA replica packages for adtrust are installed] ******************************************************************************************************************************
skipping: [ipa-2.test.<Domain>]

TASK [ipareplica : Install - Ensure that firewall packages installed] ********************************************************************************************************************************************
ok: [ipa-2.test.<Domain>]

TASK [ipareplica : Firewalld service - Ensure that firewalld is running] *****************************************************************************************************************************************
ok: [ipa-2.test.<Domain>]

TASK [ipareplica : Firewalld - Verify runtime zone "{{ ipareplica_firewalld_zone }}"] ****************************************************************************************************************************
skipping: [ipa-2.test.<Domain>]

TASK [ipareplica : Firewalld - Verify permanent zone "{{ ipareplica_firewalld_zone }}"] **************************************************************************************************************************
skipping: [ipa-2.test.<Domain>]

TASK [ipareplica : Install - Set ipareplica_servers] *************************************************************************************************************************************************************
skipping: [ipa-2.test.<Domain>]

TASK [ipareplica : Install - Set default principal if no keytab is given] ****************************************************************************************************************************************
skipping: [ipa-2.test.<Domain>]

TASK [ipareplica : Install - Replica installation test] **********************************************************************************************************************************************************
fatal: [ipa-2.test.<Domain>]: FAILED! => {"changed": false, "msg": "common_check() missing 2 required positional arguments: 'skip_mem_check' and 'setup_ca'"}

PLAY RECAP *******************************************************************************************************************************************************************************************************
ipa-2.test.<Domain>         : ok=6    changed=0    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0   
```

**Comment by rjeffman** [comment] 2020-11-23 20:00
@jasperroloff I was able to reproduce it.

The issue is caused by changes in recent FreeIPA versions (I tracked it to 4.8.10), which break compatibility wit ipareplica role.

I'm marking it as a bug, and will work on it as soon as I can.

**Closed** 2020-11-25 20:39 UTC
Labels: bug
