### ISSUE TITLE
ipahbacrule sometimes fails with 'This entry is already a member'

### ISSUE THREAD

**Issue by nirik** [freeipa/ansible-freeipa#834] opened 2022-05-19 20:49 UTC
We have a playbook with a task: 

```
- name: "Let everybody run sudo"
  delegate_to: "{{ item }}"
  ipahbacrule:
    name: "all-users/sudo"
    description: "Allow all users to execute the sudo command"
    state: present
    ipaadmin_password: "{{ ipa_server_admin_passwords[item] }}"
    hostcategory: "all"
    usercategory: "all"
    hbacsvcgroup:
      - Sudo
  notify: clean sss caches
  no_log: true
  loop: "{{ ipa_servers }}"
  when: ipa_servers is defined
```

ipa_servers is either our first prod ipa server, or first stg ipa server or both. 

With ansible-freeipa-0.3.8-1.el8 things work fine every time. 
With either ansible-freeipa-1.6.3-1.el8 or ansible-freeipa-1.7.0-1.el8 (built from fedora), it _sometimes_, but not always fails with: 

```
TASK [ipa/client : Let everybody run sudo] *************************************                    
Thursday 19 May 2022  18:55:30 +0000 (0:00:00.149)       0:05:18.589 **********                     
Thursday 19 May 2022  18:55:30 +0000 (0:00:00.149)       0:05:18.589 **********                     
failed: [ipa01.iad2.fedoraproject.org] (item=ipa01.iad2.fedoraproject.org) => {"ansible_loop_var": "item", "changed": false, "item": "ipa01.iad2.fedoraproject.org", "msg": "hbacrule_add_service: hbacsvc group sudo: This entry is already a member"}                                                        
failed: [ipa01.iad2.fedoraproject.org -> ipa01.stg.iad2.fedoraproject.org] (item=ipa01.stg.iad2.fedoraproject.org) => {"ansible_loop_var": "item", "changed": false, "item": "ipa01.stg.iad2.fedoraproject.org", "msg": "hbacrule_add_service: hbacsvcgroup sudo: This entry is already a member"}
```

Happy to get more info or try things. Thanks.

**Comment by rjeffman** [comment] 2022-05-20 00:05
This is interesting, as this error did occur before, and should've been fixed by #686.

I'm marking this as a bug, and will be looking into it next week.

**Comment by rjeffman** [comment] 2023-02-11 01:43
@nirik, I'm still no able to reproduce this issue.

I have one question, is the bug reproducible when `ipa_servers` is only one of the servers or is it only reproducible when it is more than one?

You should not loop through the servers, as changes should  be made only to a single server and you should let replication kick in and replicate the changes to the other replicas. By looping through the servers you risk to incur in concurrent changes which may end up with the result you see.

**Comment by nirik** [comment] 2023-02-11 18:04
It should be only one server. ;) 

I'll put this on my list to upgrade and re-test next week... Thanks for working on it!

**Comment by nirik** [comment] 2023-02-13 23:39
ok. It might be something with our ipa setup... I'm not sure, but I have more information anyhow: 

* It fails exactly every other time. works, fails, works, fails, works, fails. 
* I can duplicate it with just a command line call:
```
# ansible -m ipahbacrule -a "name=all-users/sudo description='Allow all users to execute the sudo command' state=present hostcategory=all usercategory=all hbacsvcgroup=sudo ipaadmin_password=redacted" ipa01.iad2.fedoraproject.org
ipa01.iad2.fedoraproject.org | CHANGED => {
    "changed": true
}
# ansible -m ipahbacrule -a "name=all-users/sudo description='Allow all users to execute the sudo command' state=present hostcategory=all usercategory=all hbacsvcgroup=sudo ipaadmin_password=redacted" ipa01.iad2.fedoraproject.org
ipa01.iad2.fedoraproject.org | FAILED! => {
    "changed": false,
    "msg": "hbacrule_add_service: hbacsvcgroup sudo: This entry is already a member"
}
# ansible -m ipahbacrule -a "name=all-users/sudo description='Allow all users to execute the sudo command' state=present hostcategory=all usercategory=all hbacsvcgroup=sudo ipaadmin_password=redacted" ipa01.iad2.fedoraproject.org
ipa01.iad2.fedoraproject.org | CHANGED => {
    "changed": true
}
# ansible -m ipahbacrule -a "name=all-users/sudo description='Allow all users to execute the sudo command' state=present hostcategory=all usercategory=all hbacsvcgroup=sudo ipaadmin_password=redacted" ipa01.iad2.fedoraproject.org
ipa01.iad2.fedoraproject.org | FAILED! => {
    "changed": false,
    "msg": "hbacrule_add_service: hbacsvcgroup sudo: This entry is already a member"
}
```

Happy to try and get more info if you can tell me how. ;)

**Comment by rjeffman** [comment] 2023-02-14 11:53
I could reproduce and found the issue. It is not only your setup, but it is helping to trigger the issue.

The issue is triggered by having an hbacrule with uppercase letter. Since we only convert module parameters to lowercase, it fail once, succeds once, because it tries to add the `sudo` hbacsvcgroup to the list of groups, and find that `Sudo` is already there, but since `Sudo` is not on the module parameter list, it tries to remove it. 

Here is the list of commands executed:
* `['all-users/sudo', 'hbacrule_add_service', {'hbacsvc': [], 'hbacsvcgroup': ['sudo']}]`
* `['all-users/sudo', 'hbacrule_remove_service', {'hbacsvc': [], 'hbacsvcgroup': ['Sudo']}]`

This was a weird one. It's the first time we have idempotence issues with data from IPA rather than data from the module parameters.

I'm about to get some time off and plan to work on this issue in march.

Sorry for not being able to fix it earlier.

Thank you very much for the report!

**Comment by nirik** [comment] 2023-02-14 16:06
Ah, I wondered about the 'S' there. ;( 

Is there any workaround? can we delete the 'Sudo' one and use 'sudo' everywhere to avoid it? Or shall we just wait for a fix?

**Comment by rjeffman** [comment] 2023-02-14 17:54
Unless it is blocking you, I suggest you wait for a fix (should come by end of March, begining of April).

If you need it by now, recreating the `hbacsvcgroup` as `sudo` could be used as a workaround.

Unfortunatelly, even if I had the time now, the proper fix would not be released much faster than the current plan (I was already working on a change related to it, it just make this slightly more complicated).

**Comment by nirik** [comment] 2023-02-14 18:48
No problem at all. We can recreate the svcgroup or just downgrade for now. 

Thanks!

**Comment by nirik** [comment] 2023-02-14 20:50
Thanks. That worked fine here too. :)

**Comment by ebarrere** [comment] 2023-02-16 16:55
FYI, it appears this also occurs with the ipagroup module. I'm happy to help with testing/troubleshooting if needed.

**Comment by rjeffman** [comment] 2023-02-17 11:25
This will happen with all modules that have groups (user or host groups), users, hosts, and some other data. This is a serious bug that I'm already addressing.

**Comment by ebarrere** [comment] 2023-02-17 14:37
Great — thanks for the heads up!

**Closed** 2024-02-09 18:49 UTC
Labels: bug, idempotence
