### ISSUE TITLE
sudorule runasuser with external user ("root") is not idempotent

### ISSUE THREAD

**Issue by sigbjornaib** [freeipa/ansible-freeipa#679] opened 2021-11-05 13:50 UTC
The ipasudorule module fails with error "sudorule_add_runasuser: user root: This entry is already a member" when using the ipasudorule module, and the external user specified happens to already be present in the sudorule.

An example of the task:

```
- name: "Create/Update SUDO Rule with Run Commands and As Whom"
  freeipa.ansible_freeipa.ipasudorule:
    name: "{{ sudorule.name }}"
    description: "{{ sudorule.description }}"
    cmdcategory: ""
    runasusercategory: ""
    runasgroupcategory: ""
    allow_sudocmd:
      - 'ALL'
    runasuser:
      - 'root'
    action: sudorule
    state: present
  loop: "{{ ipa_sudorules }}"
  loop_control:
    loop_var: sudorule
```

**Comment by rjeffman** [comment] 2021-11-06 19:22
Closing as a duplicate of #664. PR #665 was proposed as a fix for the issue.

**Closed by rjeffman** 2021-11-06 19:22 UTC
