### ISSUE TITLE
ipahost does not work when ipaserver_setup_dns=False

### ISSUE THREAD

**Issue by romainrbr** [freeipa/ansible-freeipa#371] opened 2020-08-24 19:32 UTC
Hello,

It seems that we can't use the `ipahost` module if the FreeIPA server was installed without DNS :

```
- freeipa.ansible_freeipa.ipahost:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: test.test.tech # The server can resolve this hostname
    force: yes
    state: present
```

Server was setup using the `install-server.yml` playbook, with only the following variables : 
```
 ipaadmin_password=ADMPassword1 ipadm_password=DMPassword1 ipaserver_domain=TEST.tech ipaserver_realm=TEST.TECH
```

Ansible's output : 

```
fatal: [ipa.test.tech]: FAILED! => {"changed": false, "msg": "dnsrecord_show failed: DNS is not configured"}
```

Adding the host through `ipa host-add` works without any issues.
Am I missing anything ? 

Thanks

**Comment by rjeffman** [comment] 2020-08-26 21:07
@romainrbr, is it possible to provide a playbook execution with `-vvv`?

I was not able to reproduce this issue, and there are several tests on which `force: yes` is used with module `ipahost` in the CI pipelines, and they all succeed.

**Comment by romainrbr** [comment] 2020-08-27 13:21
Hi @rjeffman , this is actually from installing FreeIPA on an empty vagrant box, with the following process : 

```
vagrant init centos/8
vagrant up
vagrant ssh
sudo hostnamectl set-hostname ipa.test.tech
sudo reboot
```

inventory file : 

```
[ipaserver]
ipa.test.tech ansible_host=127.0.0.1 ansible_ssh_private_key_file="$PATH_TO_VAGRANT_GENERATED/private_key" ansible_port=2222 ansible_user='vagrant' ipaadmin_password=ADMPassword1 ipadm_password=DMPassword1 ipaserver_domain=test.tech ipaserver_realm=TEST.TECH
```

installing the server with the official playbook `collections/ansible_collections/freeipa/ansible_freeipa/playbooks/install-server.yml`
and then running the following playbook : 

```
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true
  tasks:
  - freeipa.ansible_freeipa.ipahost:
      ipaadmin_password: "{{ ipaadmin_password }}"
      name: test.test.tech
      force: yes
      state: present
```

here is the -vvv error : 


```
TASK [freeipa.ansible_freeipa.ipahost] **********************************************************************************************************************************************************************************************
task path: /home/romain/Documents/Saagie/vagrant/freeipa-debug/test.yml:5
Thursday 27 August 2020  10:20:32 -0300 (0:00:02.357)       0:00:02.475 ******* 
Using module file /home/romain/Documents/Saagie/Ansible/ansible-saagie-infra/collections/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipahost.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=30s -o ConnectionAttempts=100 -o ForwardAgent=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o Port=2222 -o 'IdentityFile="/home/romain/Documents/Saagie/vagrant/freeipa-debug/.vagrant/machines/default/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=120 -o ControlPath=/home/romain/.ansible/cp/055b8f4af0 127.0.0.1 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-nrysokgaingkcwewroepkhtpjcrxpkhw ; /usr/libexec/platform-python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<127.0.0.1> (1, '\n{"msg": "dnsrecord_show failed: DNS is not configured", "failed": true, "exception": "  File \\"/tmp/ansible_freeipa.ansible_freeipa.ipahost_payload_psa90ayp/ansible_freeipa.ansible_freeipa.ipahost_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipahost.py\\", line 452, in find_dnsrecord\\n  File \\"/tmp/ansible_freeipa.ansible_freeipa.ipahost_payload_psa90ayp/ansible_freeipa.ansible_freeipa.ipahost_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/module_utils/ansible_freeipa_module.py\\", line 170, in api_command\\n    return api.Command[command](name, **args)\\n  File \\"/usr/lib/python3.6/site-packages/ipalib/frontend.py\\", line 450, in __call__\\n    return self.__do_call(*args, **options)\\n  File \\"/usr/lib/python3.6/site-packages/ipalib/frontend.py\\", line 478, in __do_call\\n    ret = self.run(*args, **options)\\n  File \\"/usr/lib/python3.6/site-packages/ipalib/frontend.py\\", line 800, in run\\n    return self.execute(*args, **options)\\n  File \\"/usr/lib/python3.6/site-packages/ipaserver/plugins/baseldap.py\\", line 1319, in execute\\n    dn = self.obj.get_dn(*keys, **options)\\n  File \\"/usr/lib/python3.6/site-packages/ipaserver/plugins/dns.py\\", line 3164, in get_dn\\n    raise errors.NotFound(reason=_(\'DNS is not configured\'))\\n", "invocation": {"module_args": {"force": true, "ipaadmin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "state": "present", "name": ["test.test.tech"], "ipaadmin_principal": "admin", "action": "host", "hosts": null, "update_password": null, "description": null, "locality": null, "location": null, "platform": null, "os": null, "password": null, "random": null, "certificate": null, "managedby_host": null, "principal": null, "allow_create_keytab_user": null, "allow_create_keytab_group": null, "allow_create_keytab_host": null, "allow_create_keytab_hostgroup": null, "allow_retrieve_keytab_user": null, "allow_retrieve_keytab_group": null, "allow_retrieve_keytab_host": null, "allow_retrieve_keytab_hostgroup": null, "mac_address": null, "sshpubkey": null, "userclass": null, "auth_ind": null, "requires_pre_auth": null, "ok_as_delegate": null, "ok_to_auth_as_delegate": null, "reverse": null, "ip_address": null, "update_dns": null}}, "warnings": ["Module did not set no_log for update_password"]}\n', '')
<127.0.0.1> Failed to connect to the host via ssh: 
The full traceback is:
  File "/tmp/ansible_freeipa.ansible_freeipa.ipahost_payload_psa90ayp/ansible_freeipa.ansible_freeipa.ipahost_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipahost.py", line 452, in find_dnsrecord
  File "/tmp/ansible_freeipa.ansible_freeipa.ipahost_payload_psa90ayp/ansible_freeipa.ansible_freeipa.ipahost_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/module_utils/ansible_freeipa_module.py", line 170, in api_command
    return api.Command[command](name, **args)
  File "/usr/lib/python3.6/site-packages/ipalib/frontend.py", line 450, in __call__
    return self.__do_call(*args, **options)
  File "/usr/lib/python3.6/site-packages/ipalib/frontend.py", line 478, in __do_call
    ret = self.run(*args, **options)
  File "/usr/lib/python3.6/site-packages/ipalib/frontend.py", line 800, in run
    return self.execute(*args, **options)
  File "/usr/lib/python3.6/site-packages/ipaserver/plugins/baseldap.py", line 1319, in execute
    dn = self.obj.get_dn(*keys, **options)
  File "/usr/lib/python3.6/site-packages/ipaserver/plugins/dns.py", line 3164, in get_dn
    raise errors.NotFound(reason=_('DNS is not configured'))
[WARNING]: Module did not set no_log for update_password
fatal: [ipa.test.tech]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "action": "host", 
            "allow_create_keytab_group": null, 
            "allow_create_keytab_host": null, 
            "allow_create_keytab_hostgroup": null, 
            "allow_create_keytab_user": null, 
            "allow_retrieve_keytab_group": null, 
            "allow_retrieve_keytab_host": null, 
            "allow_retrieve_keytab_hostgroup": null, 
            "allow_retrieve_keytab_user": null, 
            "auth_ind": null, 
            "certificate": null, 
            "description": null, 
            "force": true, 
            "hosts": null, 
            "ip_address": null, 
            "ipaadmin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "ipaadmin_principal": "admin", 
            "locality": null, 
            "location": null, 
            "mac_address": null, 
            "managedby_host": null, 
            "name": [
                "test.test.tech"
            ], 
            "ok_as_delegate": null, 
            "ok_to_auth_as_delegate": null, 
            "os": null, 
            "password": null, 
            "platform": null, 
            "principal": null, 
            "random": null, 
            "requires_pre_auth": null, 
            "reverse": null, 
            "sshpubkey": null, 
            "state": "present", 
            "update_dns": null, 
            "update_password": null, 
            "userclass": null
        }
    }, 
    "msg": "dnsrecord_show failed: DNS is not configured"
}
```

```
❯ ansible --version
/home/romain/.pyenv/versions/2.7.17/envs/ansible-2.9/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
ansible 2.9.12
  config file = /home/romain/Documents/Saagie/Ansible/ansible-saagie-infra/ansible.cfg
  configured module search path = [u'/home/romain/Documents/Saagie/Ansible/ansible-saagie-infra/plugins/modules']
  ansible python module location = /home/romain/.pyenv/versions/2.7.17/envs/ansible-2.9/lib/python2.7/site-packages/ansible
  executable location = /home/romain/.pyenv/versions/ansible-2.9/bin/ansible
  python version = 2.7.17 (default, Dec 16 2019, 10:54:35) [GCC 9.2.1 20191008]

```
I am running python 2.7 because of the collection bug.

**Comment by t-woerner** [comment] 2020-09-03 14:15
Which ansible-freeipa version are you using?

**Comment by romainsaagie** [comment] 2020-09-03 14:17
Latest version, installed through : `ansible-galaxy collection install freeipa.ansible_freeipa --force`

With this line in my ansible.cfg : `collections_paths = collections`

**Comment by romainrbr** [comment] 2020-09-03 14:18
Latest version, installed through : `ansible-galaxy collection install freeipa.ansible_freeipa --force`

With this line in my ansible.cfg : `collections_paths = collections`

**Comment by t-woerner** [comment] 2020-09-08 10:26
Please verify that you are using version ansible-freeipa 0.1.12. It provided a fix for this issue.

**Comment by romainrbr** [comment] 2020-09-08 11:38
All those test were made with collection 0.1.12 : 

```
❯ cat MANIFEST.json 
{
 "collection_info": {
  "namespace": "freeipa",
  "name": "ansible_freeipa",
  "version": "0.1.12",
  "authors": [
   "Thomas Woerner <twoerner@redhat.com>"
  ],
  "readme": "README.md",
  "tags": [
   "system",
   "identity",
   "ipa",
   "freeipa",
   "cluster",
   "collection"
  ],
  "description": "Ansible roles and modules for FreeIPA",
  "license": [
   "GPL-3.0-or-later"
  ],
  "license_file": null,
  "dependencies": null,
  "repository": "https://github.com/freeipa/ansible-freeipa",
  "documentation": "https://github.com/freeipa/ansible-freeipa/blob/master/README.md",
  "homepage": "https://github.com/freeipa/ansible-freeipa",
  "issues": "https://github.com/freeipa/ansible-freeipa/issues"
 },
 "file_manifest_file": {
  "name": "FILES.json",
  "ftype": "file",
  "chksum_type": "sha256",
  "chksum_sha256": "b80b16115abcf69978ea63a0b0c3ab6e8b5da539c4a21f08f64a2987c9a94a2a",
  "format": 1
 },
 "format": 1
}%                                          
```

**Comment by Thulium-Drake** [comment] 2020-10-13 20:45
This problem persists in version 0.2.1 of the collection:

```
<ipa.infra.htm.lab> (0, b'/home/ansible\n', b'')
<ipa.infra.htm.lab> ESTABLISH SSH CONNECTION FOR USER: ansible
<ipa.infra.htm.lab> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/c6cdfc2c07 ipa.infra.htm.lab '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp `"&& mkdir "` echo /home/ansible/.ansible/tmp/ansible-tmp-1602621818.7348063-19328-34851949457959 `" && echo ansible-tmp-1602621818.7348063-19328-34851949457959="` echo /home/ansible/.ansible/tmp/ansible-tmp-1602621818.7348063-19328-34851949457959 `" ) && sleep 0'"'"''
<ipa.infra.htm.lab> (0, b'ansible-tmp-1602621818.7348063-19328-34851949457959=/home/ansible/.ansible/tmp/ansible-tmp-1602621818.7348063-19328-34851949457959\n', b'')
Using module file /root/projects/htm/collections/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipahost.py
<ipa.infra.htm.lab> PUT /root/.ansible/tmp/ansible-local-19301szkizaoz/tmpnad77nm6 TO /home/ansible/.ansible/tmp/ansible-tmp-1602621818.7348063-19328-34851949457959/AnsiballZ_ipahost.py
<ipa.infra.htm.lab> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/c6cdfc2c07 '[ipa.infra.htm.lab]'
<ipa.infra.htm.lab> (0, b'sftp> put /root/.ansible/tmp/ansible-local-19301szkizaoz/tmpnad77nm6 /home/ansible/.ansible/tmp/ansible-tmp-1602621818.7348063-19328-34851949457959/AnsiballZ_ipahost.py\n', b'')
<ipa.infra.htm.lab> ESTABLISH SSH CONNECTION FOR USER: ansible
<ipa.infra.htm.lab> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/c6cdfc2c07 ipa.infra.htm.lab '/bin/sh -c '"'"'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1602621818.7348063-19328-34851949457959/ /home/ansible/.ansible/tmp/ansible-tmp-1602621818.7348063-19328-34851949457959/AnsiballZ_ipahost.py && sleep 0'"'"''
<ipa.infra.htm.lab> (0, b'', b'')
<ipa.infra.htm.lab> ESTABLISH SSH CONNECTION FOR USER: ansible
<ipa.infra.htm.lab> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/c6cdfc2c07 -tt ipa.infra.htm.lab '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-xfvkzkzozrzfwrfycfxjwdilxdlzroho ; /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1602621818.7348063-19328-34851949457959/AnsiballZ_ipahost.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<ipa.infra.htm.lab> (1, b'\x1b[?1034h\r\n{"msg": "dnsrecord_show failed: DNS is not configured", "failed": true, "exception": "WARNING: The below traceback may *not* be related to the actual failure.\\n  File \\"/tmp/ansible_freeipa.ansible_freeipa.ipahost_payload_4ky5Zr/ansible_freeipa.ansible_freeipa.ipahost_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipahost.py\\", line 452, in find_dnsrecord\\n  File \\"/tmp/ansible_freeipa.ansible_freeipa.ipahost_payload_4ky5Zr/ansible_freeipa.ansible_freeipa.ipahost_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/module_utils/ansible_freeipa_module.py\\", line 170, in api_command\\n    return api.Command[command](name, **args)\\n  File \\"/usr/lib/python2.7/site-packages/ipalib/frontend.py\\", line 450, in __call__\\n    return self.__do_call(*args, **options)\\n  File \\"/usr/lib/python2.7/site-packages/ipalib/frontend.py\\", line 478, in __do_call\\n    ret = self.run(*args, **options)\\n  File \\"/usr/lib/python2.7/site-packages/ipalib/frontend.py\\", line 800, in run\\n    return self.execute(*args, **options)\\n  File \\"/usr/lib/python2.7/site-packages/ipaserver/plugins/baseldap.py\\", line 1310, in execute\\n    dn = self.obj.get_dn(*keys, **options)\\n  File \\"/usr/lib/python2.7/site-packages/ipaserver/plugins/dns.py\\", line 3164, in get_dn\\n    raise errors.NotFound(reason=_(\'DNS is not configured\'))\\n", "invocation": {"module_args": {"sshpubkey": null, "update_password": null, "force": null, "allow_retrieve_keytab_user": null, "random": null, "ok_as_delegate": null, "requires_pre_auth": null, "principal": null, "allow_create_keytab_host": null, "certificate": null, "locality": null, "ip_address": null, "ipaadmin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "ipaadmin_principal": "admin", "state": "absent", "platform": null, "ok_to_auth_as_delegate": null, "location": null, "mac_address": null, "managedby_host": null, "allow_retrieve_keytab_host": null, "allow_retrieve_keytab_hostgroup": null, "description": null, "allow_retrieve_keytab_group": null, "allow_create_keytab_group": null, "password": null, "auth_ind": null, "name": ["rkec1.infra.htm.lab"], "update_dns": null, "reverse": null, "allow_create_keytab_hostgroup": null, "hosts": null, "allow_create_keytab_user": null, "action": "host", "os": null, "userclass": null}}, "warnings": ["Module did not set no_log for update_password"]}\r\n', b'Shared connection to ipa.infra.htm.lab closed.\r\n')
<ipa.infra.htm.lab> Failed to connect to the host via ssh: Shared connection to ipa.infra.htm.lab closed.
<ipa.infra.htm.lab> ESTABLISH SSH CONNECTION FOR USER: ansible
<ipa.infra.htm.lab> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/c6cdfc2c07 ipa.infra.htm.lab '/bin/sh -c '"'"'rm -f -r /home/ansible/.ansible/tmp/ansible-tmp-1602621818.7348063-19328-34851949457959/ > /dev/null 2>&1 && sleep 0'"'"''
<ipa.infra.htm.lab> (0, b'', b'')
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_freeipa.ansible_freeipa.ipahost_payload_4ky5Zr/ansible_freeipa.ansible_freeipa.ipahost_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipahost.py", line 452, in find_dnsrecord
  File "/tmp/ansible_freeipa.ansible_freeipa.ipahost_payload_4ky5Zr/ansible_freeipa.ansible_freeipa.ipahost_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/module_utils/ansible_freeipa_module.py", line 170, in api_command
    return api.Command[command](name, **args)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 450, in __call__
    return self.__do_call(*args, **options)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 478, in __do_call
    ret = self.run(*args, **options)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 800, in run
    return self.execute(*args, **options)
  File "/usr/lib/python2.7/site-packages/ipaserver/plugins/baseldap.py", line 1310, in execute
    dn = self.obj.get_dn(*keys, **options)
  File "/usr/lib/python2.7/site-packages/ipaserver/plugins/dns.py", line 3164, in get_dn
    raise errors.NotFound(reason=_('DNS is not configured'))
failed: [ipa.infra.htm.lab] (item=rkec1.infra.htm.lab) => changed=false 
  ansible_loop_var: host
  host: rkec1.infra.htm.lab
  invocation:
    module_args:
      action: host
      allow_create_keytab_group: null
      allow_create_keytab_host: null
      allow_create_keytab_hostgroup: null
      allow_create_keytab_user: null
      allow_retrieve_keytab_group: null
      allow_retrieve_keytab_host: null
      allow_retrieve_keytab_hostgroup: null
      allow_retrieve_keytab_user: null
      auth_ind: null
      certificate: null
      description: null
      force: null
      hosts: null
      ip_address: null
      ipaadmin_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      ipaadmin_principal: admin
      locality: null
      location: null
      mac_address: null
      managedby_host: null
      name:
      - rkec1.infra.htm.lab
      ok_as_delegate: null
      ok_to_auth_as_delegate: null
      os: null
      password: null
      platform: null
      principal: null
      random: null
      requires_pre_auth: null
      reverse: null
      sshpubkey: null
      state: absent
      update_dns: null
      update_password: null
      userclass: null
  msg: 'dnsrecord_show failed: DNS is not configured'

```

**Comment by Thulium-Drake** [comment] 2020-11-05 10:45
ping @rjeffman I updated the issue with a traceback as requested :-)

**Comment by rjeffman** [comment] 2020-11-05 23:35
Thank you @Thulium-Drake. Sorry, but I can't look at before November, 9th. But I'll sure look to it then.

**Comment by rjeffman** [comment] 2020-11-10 20:28
This is an issue with the way ipahost search for configured hosts. I've mistakenly opened issue #434 about it, as I thought it was a different issue, as I was having different issues with collections.

As I have a reproducer, we can now work on this issue.

**Comment by rjeffman** [comment] 2020-11-11 00:27
PR #435 is a proposal to fix this issue.

**Comment by rjeffman** [comment] 2020-11-25 22:42
ansible-freeipa 0.3.0 has been released and has a fix for this issue.

If it does not work for you, please reopen this issue and let us know.

**Closed by rjeffman** 2020-11-25 22:42 UTC
Labels: pr-avaiable
