### ISSUE TITLE
py3test.rc == 0

### ISSUE THREAD

**Issue by fmontaldo** [freeipa/ansible-freeipa#49] opened 2018-11-16 20:54 UTC
Hi

I am running the playbook under AWX and this error occur when I try to check the playbook with install-server.yml. This is the error:

TASK [ipaserver : Set python interpreter to 3] *********************************
task path: /var/lib/awx/projects/ansible-freeipa/roles/ipaserver/tasks/python_2_3_test.yml:8
fatal: [ipaserver.lab.com]: FAILED! => {
    "msg": "The conditional check 'py3test.rc == 0' failed. The error was: error while evaluating conditional (py3test.rc == 0): 'dict object' has no attribute 'rc'\n\nThe error appears to have been in '/var/lib/awx/projects/ansible-freeipa/roles/ipaserver/tasks/python_2_3_test.yml': line 8, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Set python interpreter to 3\n    ^ here\n"
}

**Comment by t-woerner** [comment] 2018-11-22 14:32
Do you also have this issue if you are using the ansible command line client?

**Comment by chicofranchico** [comment] 2019-01-22 12:44
I have the same issue when running ipaclient in check mode

**Comment by scaronni** [comment] 2019-03-08 12:49
same same here...

**Comment by scaronni** [comment] 2019-03-08 12:51
Instead of executing the script module, checking if the script explodes or runs and then set the interpreter accordingly, wouldn't be easier to just check if `/usr/bin/python3` is available and then set Python 3 as the interpreter? It all looks a bit convoluted for nothing.

**Comment by t-woerner** [comment] 2019-03-08 16:23
No the simple existence of /usr/bin/python3 does not provide enough information if the freeipa bindings are available and also installed for python3. This heavily depends on the distribution and also the used freeipa version. Usable python3 bindings are only available since freeipa-4.6.0.

The issue is that the script py3test.py is not executed in check_mode, but it needs to be. So I will fix this by adding check_mode: no to the execution of the script. Additionally the block after the initial tests in install.yml of the ipaclient, ipareplica and ipaserver role need an extra when: not ansible_check_mode. Also some additional changes to the test modules are needed to make sure that there is no change in the test and also that the check_mode is always supported in these modules.

Then the check_mode will work as expected with ipaserver, ipareplica and ipaclient.

**Comment by t-woerner** [comment] 2019-04-03 17:08
This should be fixed with the commits 82588026bf8c52d4a2bf8c4ac877625144c594d7 and 4557292743497716a44692d26ffd483c5501518c

**Closed** 2019-04-26 14:32 UTC
Labels: bug
