### ISSUE TITLE
Error installing freeipa server - cannot connect to https://xxx.yy:8443/ca/rest/account/login

### ISSUE THREAD

**Issue by LucaPrete** [freeipa/ansible-freeipa#72] opened 2019-04-16 14:38 UTC
Hello everyone,

We're using this playbook to install a FreeIPA server (master) on an Ubuntu 18.04LTS.
Everything goes well until I hit the task `TASK [ipaserver : Install - Setup CA]`.

This is the output:

```
TASK [ipaserver : Install - Setup CA] ********************************************************************************************************************************************************************************************************
fatal: [10.0.254.201]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.0.254.201 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/XXX/.ansible/tmp/ansible-tmp-1555423433.79043-184703110138725/AnsiballZ_ipaserver_setup_ca.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/XXX/.ansible/tmp/ansible-tmp-1555423433.79043-184703110138725/AnsiballZ_ipaserver_setup_ca.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/XXX/.ansible/tmp/ansible-tmp-1555423433.79043-184703110138725/AnsiballZ_ipaserver_setup_ca.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_ipaserver_setup_ca_payload_fJcQp3/__main__.py\", line 239, in <module>\r\n  File \"/tmp/ansible_ipaserver_setup_ca_payload_fJcQp3/__main__.py\", line 209, in main\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/ca.py\", line 326, in install_step_0\r\n    use_ldaps=standalone)\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/cainstance.py\", line 473, in configure_instance\r\n    self.start_creation(runtime=runtime)\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/service.py\", line 555, in start_creation\r\n    run_step(full_msg, method)\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/service.py\", line 541, in run_step\r\n    method()\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/cainstance.py\", line 1791, in migrate_profiles_to_ldap\r\n    _create_dogtag_profile(profile_id, profile_data, overwrite=False)\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/cainstance.py\", line 1797, in _create_dogtag_profile\r\n    with api.Backend.ra_certprofile as profile_api:\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/plugins/dogtag.py\", line 1296, in __enter__\r\n    method='GET'\r\n  File \"/usr/lib/python2.7/dist-packages/ipapython/dogtag.py\", line 167, in https_request\r\n    method=method, headers=headers)\r\n  File \"/usr/lib/python2.7/dist-packages/ipapython/dogtag.py\", line 229, in _httplib_request\r\n    raise NetworkError(uri=uri, error=str(e))\r\nipalib.errors.NetworkError: cannot connect to 'https://freeipa-master-01.XXX.YY:8443/ca/rest/account/login': [Errno 111] Connection refused\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
	to retry, use: --limit @/Users/XXX/ansible-freeipa/install-server.retry
```

Basically, the error is:

```
...
cannot connect to 'https://freeipa-master-01.XXX.YY:8443/ca/rest/account/login
...
```

AFAIK, there's a known issue on Ubuntu. For example, you can look for 8443 here `https://themeanti.me/technology/2018/02/21/installing-freeipa.html`.
It says to modify `/usr/lib/python2.7/dist-packages/ipaserver/install/cainstance.py` adding a timeout in two methods:

```
from __future__ import print_function
...
import time
...
 
...
def __import_ca_chain(self):
    time.sleep(10)
...
 
...
def migrate_profiles_to_ldap():
   time.sleep(10)
...
```

Unfortunately, I can't find any `__import_ca_chain(self):` method. I've tried to add the timeout in the latter, but the error keeps showing up.

Any idea how can I fix the issue and move forward?

Thanks,

-Luca

**Comment by t-woerner** [comment] 2019-04-16 16:05
__import_ca_chain is available in ipaserver/install/cainstance.py only up to FreeIPA version 4.4.4. It has been removed with https://github.com/freeipa/freeipa/commit/822e1bc82af3a6c1556546c4fbe96eeafad45762 in Oct 2016. 

There are some possible solutions to address the timeout issue. The IPA team will propose a solution that can be tested.

**Comment by LucaPrete** [comment] 2019-04-16 16:18
Thomas, thanks!
All the team looks forward to it, as it's blocking an entire deployment.

Il giorno mar 16 apr 2019 alle ore 18:05 Thomas Woerner <
notifications@github.com> ha scritto:

**Comment by tiran** [comment] 2019-04-16 16:23
Thomas, Ubuntu is running an early pre-release of 4.7.0 from 2018:

```
# head -n2 /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
# python2
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipapython.version
>>> ipapython.version.VERSION
'4.6.90.pre1+git20180411'
```

**Comment by abbra** [comment] 2019-04-16 16:32
@LucaPrete, could you please try a patch from https://github.com/freeipa/freeipa/pull/3045 ?

**Comment by LucaPrete** [comment] 2019-04-16 16:43
@abbra sure let me give it a try ;)

**Comment by LucaPrete** [comment] 2019-04-16 17:00
@abbra I'm using the ansible-playbook for the installation, so I've modified the file `/usr/lib/python2.7/dist-packages/ipaserver/install/dogtaginstance.py` manually following your patch. I've then run uninstall, then install again. Unfortunately, now the installation fails even before than getting to the point that was causing issues before:

```
TASK [ipaserver : Install - Master password creation] ****************************************************************************************************************************************************************************************
fatal: [XXXXXXXXXX]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
	to retry, use: --limit @/Users/XXXX/ansible-freeipa/install-server.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
XXXXXXXXXXXX               : ok=7    changed=0    unreachable=0    failed=1
```

As you can see I'm quite blind at this point. Any chance we can augment the log level so I can give you more info?

**Comment by LucaPrete** [comment] 2019-04-16 17:11
That, unfortunately didn't do the trick... :(

```
TASK [ipaserver : Install - Setup CA] ********************************************************************************************************************************************************************************************************
fatal: [XXX]: FAILED! => {"changed": false, "module_stderr": "Shared connection to XXXX closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/XXX/.ansible/tmp/ansible-tmp-1555434043.2248058-169335567933813/AnsiballZ_ipaserver_setup_ca.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/XXX/.ansible/tmp/ansible-tmp-1555434043.2248058-169335567933813/AnsiballZ_ipaserver_setup_ca.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/XXX/.ansible/tmp/ansible-tmp-1555434043.2248058-169335567933813/AnsiballZ_ipaserver_setup_ca.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_ipaserver_setup_ca_payload_pxn3F7/__main__.py\", line 239, in <module>\r\n  File \"/tmp/ansible_ipaserver_setup_ca_payload_pxn3F7/__main__.py\", line 209, in main\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/ca.py\", line 326, in install_step_0\r\n    use_ldaps=standalone)\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/cainstance.py\", line 473, in configure_instance\r\n    self.start_creation(runtime=runtime)\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/service.py\", line 555, in start_creation\r\n    run_step(full_msg, method)\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/service.py\", line 541, in run_step\r\n    method()\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/cainstance.py\", line 1792, in migrate_profiles_to_ldap\r\n    _create_dogtag_profile(profile_id, profile_data, overwrite=False)\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/install/cainstance.py\", line 1798, in _create_dogtag_profile\r\n    with api.Backend.ra_certprofile as profile_api:\r\n  File \"/usr/lib/python2.7/dist-packages/ipaserver/plugins/dogtag.py\", line 1296, in __enter__\r\n    method='GET'\r\n  File \"/usr/lib/python2.7/dist-packages/ipapython/dogtag.py\", line 167, in https_request\r\n    method=method, headers=headers)\r\n  File \"/usr/lib/python2.7/dist-packages/ipapython/dogtag.py\", line 229, in _httplib_request\r\n    raise NetworkError(uri=uri, error=str(e))\r\nipalib.errors.NetworkError: cannot connect to 'https://freeipa-master-XXXX:8443/ca/rest/account/login': [Errno 111] Connection refused\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
	to retry, use: --limit @/Users/XXX/ansible-freeipa/install-server.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
XXX               : ok=14   changed=6    unreachable=0    failed=1
```

**Comment by tiran** [comment] 2019-04-16 17:19
There might be a bug in the Ubuntu packages of FreeIPA. Ubuntu ships an experimental pre-release of FreeIPA 4.7.0. Does a standard installation with ipa-server-install work for you?

**Comment by LucaPrete** [comment] 2019-04-16 17:22
I can give it a try..

Question: is there a way to specify the package from the ansible (even -for
now- hardcoding the version desired)?

-Luca

Il giorno mar 16 apr 2019 alle 19:19 Christian Heimes <
notifications@github.com> ha scritto:

**Comment by LucaPrete** [comment] 2019-04-16 19:13
FYI, I've tried the standard installation as well (`sudo ipa-server-install`).
As I was expecting, same issue.

```
  [23/28]: enabling CA instance
  [24/28]: migrating certificate profiles to LDAP
  [error] NetworkError: cannot connect to 'https://freeipa-master-01.XXX.YY:8443/ca/rest/account/logout': [Errno 104] Connection reset by peer
ipapython.admintool: ERROR    cannot connect to 'https://freeipa-master-01.XX.YY:8443/ca/rest/account/logout': [Errno 104] Connection reset by peer
ipapython.admintool: ERROR    The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```

Any thought about how we can get out of this?

**Comment by tiran** [comment] 2019-04-16 20:07
For some unknown reason Dogtag (pki-tomcat) fails to start. It might be a problem in the Ubuntu packages. Ubuntu uses init.d instead of systemd for pki-tomcat. https://bugs.launchpad.net/ubuntu/+source/freeipa/+bug/1769440 mentions a couple of additional issues.

We run over hundred of automated test installations on Fedora every day and haven't seen any issue in that part of the code. I suspect it's an Ubuntu specific issue, perhaps caused by init.d or old packages. Could you please open a downstream bug with Ubuntu and work with Timo Aaltonen on the issue? Neither Thomas nor Alexander and I have much experience with Ubuntu's FreeIPA packages.

**Comment by LucaPrete** [comment] 2019-04-16 20:46
I can open other tickets, but I'm missing something...

Looking at the service it seems it starts and runs perfectly.

xxxx@freeipa-master-01:~$ sudo service pki-tomcatd start
xxxx@freeipa-master-01:~$ sudo service pki-tomcatd status
● pki-tomcatd.service - LSB: Start pki-tomcatd at boot time
   Loaded: loaded (/etc/init.d/pki-tomcatd; generated)
   Active: active (running) since Tue 2019-04-16 19:12:00 UTC; 1h 32min ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 116 (limit: 4702)
   CGroup: /system.slice/pki-tomcatd.service
           └─25982 /usr/share/pki/java-home/bin/java
-Djava.util.logging.config.file=/var/lib/pki/pki-tomcat/conf/logging.properties
-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
-DRESTEASY_LIB=/usr/share/java/ -Djava.

Apr 16 19:11:54 freeipa-master-01 pki-tomcatd[25772]: SLF4J: Class path
contains multiple SLF4J bindings.
Apr 16 19:11:54 freeipa-master-01 pki-tomcatd[25772]: SLF4J: Found binding
in
[jar:file:/usr/share/java/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]
Apr 16 19:11:54 freeipa-master-01 pki-tomcatd[25772]: SLF4J: Found binding
in
[jar:file:/usr/share/java/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
Apr 16 19:11:54 freeipa-master-01 pki-tomcatd[25772]: SLF4J: See
http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Apr 16 19:11:54 freeipa-master-01 pki-tomcatd[25772]: SLF4J: Actual binding
is of type [org.slf4j.impl.JDK14LoggerFactory]
Apr 16 19:11:55 freeipa-master-01 pki-tomcatd[25772]:
----------------------------------------------
Apr 16 19:11:55 freeipa-master-01 pki-tomcatd[25772]: Imported certificate
"Server-Cert cert-pki-ca"
Apr 16 19:11:55 freeipa-master-01 pki-tomcatd[25772]:
----------------------------------------------
Apr 16 19:12:00 freeipa-master-01 pki-tomcatd[25772]:    ...done.
Apr 16 19:12:00 freeipa-master-01 systemd[1]: Started LSB: Start
pki-tomcatd at boot time.

Could there be anything else we can think about?

-Luca

Il giorno mar 16 apr 2019 alle ore 22:07 Christian Heimes <
notifications@github.com> ha scritto:

**Comment by abbra** [comment] 2019-04-16 20:54
can you share ipaserver-install.log?

**Comment by LucaPrete** [comment] 2019-04-16 21:18
Sure thing. Please, find it attached.

[ipaserver-install.log](https://github.com/freeipa/ansible-freeipa/files/3086909/ipaserver-install.log)

Wired enough that this time the error refers to a logout endpoint, rather than a login endpoint.

In any case, it seems the endpoint is not reachable, but if I try to run a wget or a curl immediately after
I get the following:

```
yyy@freeipa-master-01:~$ wget https://freeipa-master-01.mgmt.dev.xxx.yyy.internal:8443/ca/rest/account/logout --no-check-certificate
--2019-04-16 21:17:43--  https://freeipa-master-01.mgmt.dev.xxx.yyy.internal:8443/ca/rest/account/logout
Resolving freeipa-master-01.mgmt.dev.xxx.yyy.internal (freeipa-master-01.mgmt.dev.xxx.yyy.internal)... 10.0.254.201
Connecting to freeipa-master-01.mgmt.dev.xxx.yyy.internal (freeipa-master-01.mgmt.dev.xxx.yyy.internal)|10.0.254.201|:8443... connected.
WARNING: cannot verify freeipa-master-01.mgmt.dev.xxx.yyy.internal's certificate, issued by ‘CN=Certificate Authority,O=MGMT.DEV.xxx.yyy.INTERNAL’:
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 401

Username/Password Authentication Failed.
```

So, it definitely seems the service is up.

Can't really understand what's wrong here..

**Comment by abbra** [comment] 2019-04-17 06:07
The reference to a logout endpoint is OK. The code runs under a context where it automatically logins into the REST API on enter to the context and logs out on exit. The exit happens because an attempt to enable profile fails internally in dogtag and we get exception from that:

```
2019-04-16T21:09:25Z DEBUG response body '{"Attributes":{"Attribute":[]},"ClassName":"com.netscape.certsrv.base.ConflictingOperationException","Code":409,"Message":"Profile already exists"}'
2019-04-16T21:09:25Z DEBUG Error migrating 'caCMCserverCert': Request failed with status 409: Non-2xx response from CA REST API: 409. Profile already exists
2019-04-16T21:09:25Z DEBUG request POST https://freeipa-master-01.mgmt.dev.xxx.yyy.internal:8443/ca/rest/profiles/caCMCserverCert?action=enable
2019-04-16T21:09:25Z DEBUG request body ''
2019-04-16T21:09:26Z DEBUG httplib request failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ipapython/dogtag.py", line 220, in _httplib_request
    conn.request(method, uri, body=request_body, headers=headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 617, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer
```
The part about 'profile already exists' is normal, so the next step is to enable already existing profile what fails with this 'Connection reset by peer'. E.g. the issue is something in dogtag.

Could you please share `/var/log/pki/pki-tomcat/` folder? There would be files like `localhost.<date>.log` which could have errors around the time the processing happened. Also there would be `localhost_access_log.<date>.txt` that would have bunch of operations on `/ca/rest/profiles/` recorded.

**Comment by tiran** [comment] 2019-04-17 06:59
It's a bug in the service abstraction layer for Debian/Ubuntu. It doesn't implement the same wait logic as Fedora and RHEL, see https://pagure.io/freeipa/issue/7916.

**Comment by LucaPrete** [comment] 2019-04-17 07:31
Please, find the logs about pki_tomcat attached.
So, localhost-* doesn't have anything inside. I've instead put the content of the access log, and more importantly the catalina.out.

Maybe we found the issue. The catalina log complains all the time that a class is missing!

Please, have a look and let me know ;)

[pki_tomcat logs.zip](https://github.com/freeipa/ansible-freeipa/files/3088355/pki_tomcat.logs.zip)

**Comment by abbra** [comment] 2019-04-17 08:10
@LucaPrete do you have `libstax-java` installed?

**Comment by abbra** [comment] 2019-04-17 08:10
same for `liboscache-java`

**Comment by LucaPrete** [comment] 2019-04-17 08:23
None of them...I'm installing them right now, and trying again to go
through the installation.

-Luca

Il giorno mer 17 apr 2019 alle ore 10:10 Alexander Bokovoy <
notifications@github.com> ha scritto:

**Comment by LucaPrete** [comment] 2019-04-17 12:52
@abbra , I've added the two packages as suggested. Somehow better, but not yet there.
From the installation point of view I get the same error as before.

As far as the `catalina.out` log conerns, I don't get anymore errors, but a bunch of warnings like this:

```
WARNING: The web application [ca] appears to have started a thread named [profileChangeMonitor] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.Object.wait(Object.java:502)
 netscape.ldap.LDAPMessageQueue.waitForMessage(Unknown Source)
 netscape.ldap.LDAPMessageQueue.nextMessage(Unknown Source)
 netscape.ldap.LDAPSearchListener.nextMessage(Unknown Source)
 netscape.ldap.LDAPSearchResults.fetchResult(Unknown Source)
 netscape.ldap.LDAPSearchResults.hasMoreElements(Unknown Source)
 com.netscape.cmscore.profile.LDAPProfileSubsystem.run(LDAPProfileSubsystem.java:452)
 java.lang.Thread.run(Thread.java:748)
WARNING: [SetPropertiesRule]{Server/Service/Engine/Host/Valve} Setting property 'resolveHosts' to 'false' did not find a matching property.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/pki/ca/webapps/ca/WEB-INF/lib/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
WARNING: [SetPropertiesRule]{Server/Service/Engine/Host/Valve} Setting property 'resolveHosts' to 'false' did not find a matching property.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/pki/ca/webapps/ca/WEB-INF/lib/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
WARNING: [SetPropertiesRule]{Server/Service/Engine/Host/Valve} Setting property 'resolveHosts' to 'false' did not find a matching property.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/pki/ca/webapps/ca/WEB-INF/lib/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/slf4j-jdk14.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
```

I can't find anything else relevant in any other pki-tomcat log.

**Comment by tiran** [comment] 2019-04-17 13:06
The installation error is bug https://pagure.io/freeipa/issue/7916 again.

Please open two bugs on https://bugs.launchpad.net/ubuntu/, one for the missing dependency for Dogtag PKI and one for the missing wait (https://pagure.io/freeipa/issue/7916). Both issues are packaging issues on Debian/Ubuntu and not related to ansible-freeipa. Timo requires bug reports to fix the issue in the Debian/Ubuntu packages.

**Comment by t-woerner** [comment] 2019-05-03 13:26
@LucaPrete Have you opened the bugs in the ubuntu bug tracker?

**Comment by LucaPrete** [comment] 2019-05-04 06:45
Thomas,

Unfortunately I have not..sorry.
I’ll try to do so by the next week.

-Luca

Il giorno ven 3 mag 2019 alle 15:26 Thomas Woerner <notifications@github.com>
ha scritto:

**Comment by jdesbonnet** [comment] 2019-10-30 13:35
Is there any ETA on when the package in the Ubuntu 18.04 repository might work or is there any work-around procedure? ( did try doing a dist upgrade on a working freeipa on Ubuntu 16.04 but that didn't really work.

**Comment by t-woerner** [comment] 2019-11-15 15:56
I am not able to say when there will be a fix in the Ubuntu repository. @LucaPrete do you have information about this?

**Comment by LucaPrete** [comment] 2019-11-15 16:33
Unfortunately, I haven't Thomas.
We had to urgently move to something else and we haven't had time to look
any longer into this issue.

-Luca

Il giorno ven 15 nov 2019 alle ore 16:56 Thomas Woerner <
notifications@github.com> ha scritto:

**Comment by camille-rodriguez** [comment] 2020-03-04 20:02
Anything new regarding this issue? Were the bugs ever opened on the ubuntu packages?

**Comment by petercmho** [comment] 2020-06-07 06:35
I also encountered the same installation error.  Is there a fix yet?

**Comment by medinski94** [comment] 2020-10-28 00:18
Same here, any updates?

**Comment by rjeffman** [comment] 2024-01-03 12:36
Ubuntu has not fixed the issue on the packages, and up to version 18.04 are in "security maintenance only", and I don't think we'll see any change from their side. Newer versions (at least since version 20.04) are only supported as a FreeIPA client.

As there's not much we can do to fix this issue, I'm closing it. If there is anything we can do, and that I might be missing here, please, reopen it.

**Closed by rjeffman** 2024-01-03 12:36 UTC
Labels: question
