### ISSUE TITLE
sudorule_add_runasuser not idempotent 

### ISSUE THREAD

**Issue by 2342435** [freeipa/ansible-freeipa#664] opened 2021-10-20 10:55 UTC
Hello,

```
- name: sudo user1 on host1
  ipasudorule:
    ipaadmin_password: "{{ vault_ipa_admin_password }}"
    name: sudo_user1_host1_nopasswd_apache
    cmdcategory: all
    description: Allow user1 to run every command as apache with sudo without password
    host: user1.domain.com
    runasuser: apache
    sudooption:
    - '!authenticate'
    user: user1
  run_once: true

```
will work once, not twice. apache is an external/local user. However it seems to be the same with IPA users.

Appreciate your help! Thanks!

Regards

Sören

**Comment by rjeffman** [comment] 2021-10-20 17:27
To circumvent the issue, you can use `failed_when: result.failed and "This entry is already a member" not in result.message`. It is not pretty, but something you can de before the issue is fixed.

I'm marking this as a bug. Thank you for reporting.

**Comment by 2342435** [comment] 2021-10-21 18:06
Thanks for unpretty but very nice workaround. Didn't know this possibility.

I have another problem with the ipahostgroup-Module. (first run add host, second delete host)
I install the collection via ansible-galaxy, can you tell me, which information you need to know, which version/state the collection has? I am blind and don't find version info.
Then i would open a new issue.

And thanks for the fast response. 

Regards

Sören

**Comment by rjeffman** [comment] 2021-10-21 18:41
Usually the ansible-galaxy release is the same as the upstream release, and done, often, in the same day. Currently, ansible-galaxy version is 0.4.2, the latest one. It was released about a week ago.

The OS vendor and version, and the Ansible version are important. if you know, the collection version is also interesting. If you don't have the ansible-freeipa version, at least when it was installed, so we can have a hint on which version it is.

For issues with other modules and roles, please, open another issue.

**Comment by may88s** [comment] 2021-11-05 15:05
Hi,
I have 0.4.2 installed via the tarball on a RHEL7.7 EUS box with Ansible 2.9.25.
I'm getting that error on a number of the modules.
I've added the failed_when:  only I need to change the last variable to result.msg 

What I'm seeing is it I create a HBAC or sudo rule then the rule gets populated but if I rerun the module (triggering the error) the rule is changes and all the field are cleared.   User Groups/Host Groups/Service or Sudo Allow Command Group.

**Closed** 2021-11-12 12:09 UTC
Labels: bug
