### ISSUE TITLE
ansible_ipa_server.__spec__ is None

### ISSUE THREAD

**Issue by generalpax** [freeipa/ansible-freeipa#230] opened 2020-03-18 16:27 UTC
valueerror when trying to install freeipa server on rhel7:

example run:

me@server:~/git/linux_infra> ansible-playbook /home/me/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/playbooks/install-server.yml -i inventory/freeipa
[WARNING]: running playbook inside collection freeipa.ansible_freeipa

PLAY [Playbook to configure IPA servers] ************************************************************
included: /home/bla/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipaserver/tasks/install.yml for server.me.ch

TASK [ipaserver : Install - Server installation test] ***********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_server.__spec__ is None
fatal: [server.me.ch]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP ******************************************************************************************
server.me.ch    : ok=6    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

detailed error msg:

task path: /home/me/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipaserver/tasks/install.yml:46
The full traceback is:
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/home/me/.local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/me/.local/lib/python3.6/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/home/me/.local/lib/python3.6/site-packages/ansible/plugins/action/__init__.py", line 815, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/home/me/.local/lib/python3.6/site-packages/ansible/plugins/action/__init__.py", line 209, in _configure_module
    **become_kwargs)
  File "/home/me/.local/lib/python3.6/site-packages/ansible/executor/module_common.py", line 1258, in modify_module
    environment=environment)
  File "/home/me/.local/lib/python3.6/site-packages/ansible/executor/module_common.py", line 1095, in _find_module_utils
    py_module_cache, zf)
  File "/home/me/.local/lib/python3.6/site-packages/ansible/executor/module_common.py", line 731, in recursive_finder
    [os.path.join(*py_module_name[:-idx])])
  File "/home/me/.local/lib/python3.6/site-packages/ansible/executor/module_common.py", line 650, in __init__
    self.get_source()
  File "/home/me/.local/lib/python3.6/site-packages/ansible/executor/module_common.py", line 666, in get_source
    data = pkgutil.get_data(to_native(self._package_name), to_native(self._mod_name + '.py'))
  File "/usr/lib64/python3.6/pkgutil.py", line 616, in get_data
    spec = importlib.util.find_spec(package)
  File "/usr/lib64/python3.6/importlib/util.py", line 102, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_server.__spec__ is None
fatal: [server.me.ch]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

**Comment by maglo** [comment] 2020-03-19 16:37
same here

`ansible-galaxy 2.9.6` in a python3 virtual env

**Comment by Akasurde** [comment] 2020-03-20 10:41
similar to https://github.com/freeipa/ansible-freeipa/issues/181

**Comment by aneagoe** [comment] 2020-03-30 06:54
Duplicate of #144 
Workaround provided here: https://github.com/ansible/ansible/issues/68361

**Comment by seocam** [comment] 2020-04-07 20:12
Closing as duplicate. @generalpax please follow #144 and  ansible/ansible#68361 in order to get updates.

If you think your problem is different from those let us know and we'll reopen the issue.

**Closed by seocam** 2020-04-07 20:12 UTC
Labels: duplicate
