### ISSUE TITLE
freeipa.ansible_freeipa.ipaprivilege reports changed in check mode

### ISSUE THREAD

**Issue by donescup** [freeipa/ansible-freeipa#787] opened 2022-03-08 18:01 UTC
freeipa version 1.6.2

$ ansible --version
ansible [core 2.11.5] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = [ ... ]
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = ...:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Jan 22 2021, 11:41:28) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.2
  libyaml = True

Component name: freeipa

OS / Environment
controller = RHEL 8.4, target = VMware ESXi 6.7.0

Steps to Reproduce
playbook fragment:
- name: Assign customized permission role to priviledge
  freeipa.ansible_freeipa.ipaprivilege:
    ipaadmin_password: foopass
    name: "User Administrators"
    permission:
    - "Set Password Expiration"

Expected results:
TASK [ipaserver_master_configuration : Assign customized permission role to priviledge] ***
ok: [sup01]
Monday 07 March 2022  21:53:52 +0000 (0:00:03.335)       0:00:39.239 ********** 

Actual results:
TASK [ipaserver_master_configuration : Assign customized permission role to priviledge] ***
changed: [sup01]
Monday 07 March 2022  21:53:52 +0000 (0:00:03.335)       0:00:39.239 **********

**Comment by rjeffman** [comment] 2022-03-24 21:16
Hi @donescup,

I was not able to reproduce your issue.

Can you provide more details?

Below is the testing playbook I used.

```yaml
---
- name: debug
  hosts: ipaserver
  gather_facts: no

  tasks:

  - name: Ensure customized permission.
    ipapermission:
      ipaadmin_password: SomeADMINpassword
      name: "Set Password Expiration"
      object_type: user
      right: all
      attrs:
      - krbPasswordExpiration

  - name: Assign customized permission role to priviledge
    ipaprivilege:
      ipaadmin_password: SomeADMINpassword
      name: "User Administrators"
      permission:
        - "Set Password Expiration"

  - name: Assign customized permission role to priviledge
    ipaprivilege:
      ipaadmin_password: SomeADMINpassword
      name: "User Administrators"
      permission:
        - "Set Password Expiration"
    check_mode: yes
```

**Comment by donescup** [comment] 2022-03-29 20:39
I have rerun the playbook in question and I cannot duplicate it either.
I ran your example too and it works as expected.

**Comment by rjeffman** [comment] 2022-03-29 21:51
As it worked out, I'm closing this issue.

This is one kind of issue that we are working on to not happen again, so, feel free to either reopen this one, or create another (with more details) if the problem shows up again.

**Closed by rjeffman** 2022-03-29 21:51 UTC

**Comment by donescup** [comment] 2022-03-29 21:59
Sounds good, thank you.

-          Pompiliu

From: Rafael Guterres Jeffman ***@***.***>
Sent: Tuesday, March 29, 2022 5:52 PM
To: freeipa/ansible-freeipa ***@***.***>
Cc: Donescu, Pompiliu [US-US] [NON-EMP] ***@***.***>; Mention ***@***.***>
Subject: EXTERNAL: Re: [freeipa/ansible-freeipa] freeipa.ansible_freeipa.ipaprivilege reports changed in check mode (Issue #787)


CAUTION: This email originated from outside of Leidos. Be cautious when clicking or opening content.

As it worked out, I'm closing this issue.

This is one kind of issue that we are working on to not happen again, so, feel free to either reopen this one, or create another (with more details) if the problem shows up again.
