### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: No module named gssapi

### ISSUE THREAD

**Issue by alfredodeluca** [freeipa/ansible-freeipa#34] opened 2018-07-19 09:30 UTC
I got this error every time I run the ipaserver installation on vagrant!

ERROR! Unexpected Exception, this is probably a bug: No module named gssapi

**Comment by t-woerner** [comment] 2018-07-23 09:18
Which distribution are you using?
If this is Fedora, then this is unexpected as freeipa-server is requiring python3-gssapi for newer releases and python2-gssapi for older ones.

**Comment by alfredodeluca** [comment] 2018-07-23 16:21
hi there.  I used a vagrant box centos 7 latest.

/Alfredo

**Comment by mavit** [comment] 2018-08-15 13:13
Tucked away in [ipahost.py](/freeipa/ansible-freeipa/blob/master/roles/ipaclient/library/ipahost.py), it mentions that the `gssapi` module is required on the Ansible _controller_.

**Comment by meamens** [comment] 2018-09-14 12:00
But the module is installed on my machine too (or Python2 + 3 don't complain that it's missing at least). Here's my attempt a few minutes ago: -

`TASK [ipaclient : Set python interpreter to 2] *****************************************************************************************************************************
skipping: [prodbpm2]
skipping: [prodsoa2]
ERROR! Unexpected Exception, this is probably a bug: No module named gssapi
to see the full traceback, use -vvv
~/ansible ❯❯❯ python2                                                                                                                                                ✘ 250
Python 2.7.15 (default, Jul 23 2018, 21:31:33)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gssapi
>>> exit()
~/ansible ❯❯❯ python3
Python 3.7.0 (default, Jul 23 2018, 20:24:19)
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gssapi
>>> exit()`

**Comment by meamens** [comment] 2018-09-21 07:54
FYI I've ran this from a CentOS VM and don't get the gssapi error, so I guess this is a small bug affecting non-Linux machines

**Comment by nkinder** [comment] 2018-10-23 00:46
I have encountered this on a Fedora 28 (running Ansible) to set up an IPA server on a CentOS 7.x VM.  The issue is that the import of the 'gssapi' module is needed on the system running Ansible.  The freeipa-* package dependencies won't help here, as these are only being installed on the target system and may very likely not be installed on the host running Ansible.

At a minimum, requirements.txt should list gssapi as a requirement in the ansible-freeipa repo.  It would also be nice if setup.py could be updated to handle installation requirements.

**Comment by jittakal** [comment] 2019-01-08 04:37
I have encountered same error, Ansible running on CentOS 7.4, Ansible 2.5, Python 2. By default gssapi yum pckage was not installed and it is also not available `pip list`. Manually installed using `sudo yum install python-gssapi`  and verified it with `pip list | grep gssapi` on Ansible control machine, so it is one of the pre-requisite for linux. As mentioned by @nkinder have to update requirements.txt.

**Comment by trevor-viljoen** [comment] 2019-02-15 20:40
This worked for me on my Mac: `pip install python-gssapi`

**Comment by dmitryperets** [comment] 2019-03-14 10:59
I had the same issue with Mac OS Sierra and python/ansible installed via Homebrew. 
The problem turns out to be that ansible comes with its own instance of python, so when you install modules on your other instance of python, it doesn't help.

Here is an illustration. 
Let's say, you test your python as follows:
```
$ python
Python 2.7.16 (default, Mar  4 2019, 09:02:19) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gssapi
>>> exit()
```

This looks just fine. But the problem is that ansible doesn't use this instance of python, as can be seen here:
```
$ head -1 $(which ansible-playbook)
#!/usr/local/Cellar/ansible/2.7.8/libexec/bin/python3.7
```

Now if you try to check the module on THIS instance of python, you'll get your error:
```
$ /usr/local/Cellar/ansible/2.7.8/libexec/bin/python3.7
Python 3.7.2 (default, Feb 12 2019, 08:16:11) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gssapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gssapi'
```

And so, here is how you fix it:
```
$ /usr/local/Cellar/ansible/2.7.8/libexec/bin/pip install python-gssapi
```

Now you have gssapi available for the right instance of python:
```
$ /usr/local/Cellar/ansible/2.7.8/libexec/bin/python3.7
Python 3.7.2 (default, Feb 12 2019, 08:16:11) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gssapi
>>> exit()
```

It should be fine now...
So I believe there is no issue with ansible-freeipa here.

**Comment by meamens** [comment] 2019-03-26 11:33
@dmitryperets this is the solution, I worked around it but it's nice to make sense of the problem and have a working solution (which will likely need repeating if this integrated Python is updated via brew)

You legend, thanks very much Dmitry!

**Comment by t-woerner** [comment] 2020-09-03 10:56
Closing as this is an ansible Mac OS Sierra issue.

**Closed by t-woerner** 2020-09-03 10:56 UTC
Labels: bug
