### ISSUE TITLE
ipaclient install.yml fails at line 33

### ISSUE THREAD

**Issue by brianbrady** [freeipa/ansible-freeipa#113] opened 2019-08-07 00:03 UTC
I am having trouble adding a client to an existing IPA instance. 

I get a 'no action detected in task' message for line 33. I assume this has something to do with how I installed the collection. I used the 'mazer install freeipa.ansible_freeipa' as described on ansible-galaxy. Then I moved the collection from '.ansible/collections/...' into my ansible project '/project/collections/...' instead of playing with symlinks. 

I believe I have all the required variable set according to the client docs.

Did mazer screw me up? I plan to try pulling the source directly from GitHub and trying again tomorrow.

**Comment by t-woerner** [comment] 2019-08-07 07:46
Have you moved the whole collection to your collections directory? Do you have something like 
'/project/collections/freeipa/ansible_freeipa' now?

Please have a look at https://github.com/freeipa/ansible-freeipa#usage if you plan to use the github version. It is not prepared to be used as a collection directly as paths and prefixes need to be adapted for this.

**Comment by dawud** [comment] 2020-01-06 19:52
@brianbrady @t-woerner OK to close this one as duplicate of #180 given the changes in the repository and `ansible-galaxy` itself since this was opened?

Thanks!

**Comment by brianbrady** [comment] 2020-01-07 15:53
Ok to close

Regards,

Brian Brady
Consulting Architect

VMware
VMware Federal, National Security

719.339.6484 Mobile
720.744.7218 Office
834.1124 Secure
________________________________

**Closed** 2020-01-07 17:00 UTC
Labels: duplicate, question
