### ISSUE TITLE
'ValueError' during execution of molecule test (docker driver)

### ISSUE THREAD

**Issue by beargiles** [freeipa/ansible-freeipa#266] opened 2020-05-08 21:42 UTC
I'm hitting a 'ValueError' when running a molecule test on freeipa.ansible_freeipa.ipaserver.

Verbose output:

    <ipa.devops.snapdevteam.com> ESTABLISH DOCKER CONNECTION FOR USER: root
    <ipa.devops.snapdevteam.com> EXEC ['/usr/bin/docker', b'exec', b'-i', 'ipa.devops.snapdevteam.com', '/bin/sh', '-c', "/bin/sh -c 'echo ~ && sleep 0'"]
    <ipa.devops.snapdevteam.com> EXEC ['/usr/bin/docker', b'exec', b'-i', 'ipa.devops.snapdevteam.com', '/bin/sh', '-c', '/bin/sh -c \'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1588971368.5493798-6671-236583064439228 && echo ansible-tmp-1588971368.5493798-6671-236583064439228="` echo /root/.ansible/tmp/ansible-tmp-1588971368.5493798-6671-236583064439228 `" ) && sleep 0\'']
    <ipa.devops.snapdevteam.com> EXEC ['/usr/bin/docker', b'exec', b'-i', 'ipa.devops.snapdevteam.com', '/bin/sh', '-c', "/bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1588971368.5493798-6671-236583064439228/ > /dev/null 2>&1 && sleep 0'"]
    The full traceback is:
    Traceback (most recent call last):
        File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
    File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
    File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
    File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 815, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
    File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 209, in _configure_module
    **become_kwargs)
    File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/module_common.py", line 1258, in modify_module
    environment=environment)
    File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/module_common.py", line 1095, in _find_module_utils
    py_module_cache, zf)
    File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/module_common.py", line 731, in recursive_finder
    [os.path.join(*py_module_name[:-idx])])
    File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/module_common.py", line 650, in __init__
    self.get_source()
    File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/module_common.py", line 666, in get_source
    data = pkgutil.get_data(to_native(self._package_name), to_native(self._mod_name + '.py'))
    File "/usr/lib/python3.7/pkgutil.py", line 619, in get_data
    spec = importlib.util.find_spec(package)
    File "/home/bgiles/.molecule.venv/lib/python3.7/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
    ValueError: 
        ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_server.__spec__ is None
    fatal: [ipa.devops.snapdevteam.com]: FAILED! => {
        "msg": "Unexpected failure during module execution.",
        "stdout": ""
    }

The play is

    - name: install freeipa
      vars:
        # base variables
        ipaserver: '{{ fqdn }}'
        ipadm_password: '{{ dm_password }}'
        ipaadmin_password: '{{ admin_password }}'
        ipaserver_domain: '{{ domain }}'
        ipaserver_realm: '{{ domain | upper }}'
        ipaserver_hostname: '{{ fqdn }}'
    
        # server variables
        ipaserver_setup_kra: yes
        ipaserver_setup_dns: yes
    
        # client variables
        ipaclient_mkhomedir: yes
    
        # certificate system variables
        ipaserver_subject_base: '{{ subject_base }}'
        ipaserver_ca_subject: '{{ ca_subject }}'
    
        # dns variables
        ipaserver_auto_reverse: yes
        ipaserver_auto_forwarders: yes
    
        # special variables
        ipaserver_setup_firewalld: no
      import_role:
        name: freeipa.ansible_freeipa.ipaserver

the vars are

    admin_password: password
    hostname: ipa
    domain: devops.snapdevteam.com
    fqdn: '{{ hostname }}.{{ domain }}'
    dm_password: password
    subject_base: 'dc=devops,dc=snapdevteam,dc=com' 
    ca_subject: 'cn=Certificate Authority,{{ subject_base }}'

and molecule.yml contains

    platforms:
      - name: ipa.devops.snapdevteam.com
        image: geerlingguy/docker-centos7-ansible:latest
        pre_build_image: true
        privileged: true
        command: /sbin/init
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
         
I'm using ansible 2.9.7 and molecule 3.0.4.

If I change 'ipaserver_setup_kra' and 'ipaserver_setup_dns' to no I get further

    TASK [ipaserver : Install - Ensure that IPA server packages are installed] *****
     ok: [ipa.devops.snapdevteam.com] => {
          "changed": false,
          "invocation": {
              "module_args": {
                  "allow_downgrade": false,
                  "autoremove": false,
                  "bugfix": false,
                  "conf_file": null,
                  "disable_excludes": null,
                  "disable_gpg_check": false,
                  "disable_plugin": [],
                  "disablerepo": [],
                  "download_dir": null,
                  "download_only": false,
                  "enable_plugin": [],
                  "enablerepo": [],
                  "exclude": [],
                  "install_repoquery": true,
                  "install_weak_deps": true,
                  "installroot": "/",
                  "list": null,
                  "lock_timeout": 30,
                  "name": [
                      "ipa-server",
                      "libselinux-python"
                  ],
                  "releasever": null,
                  "security": false,
                  "skip_broken": false,
                  "state": "present",
                  "update_cache": false,
                  "update_only": false,
                  "use_backend": "auto",
                  "validate_certs": true
              }
          },
          "msg": "",
          "rc": 0,
          "results": [
              "ipa-server-4.6.6-11.el7.centos.x86_64 providing ipa-server is already installed",
              "libselinux-python-2.5-15.el7.x86_64 providing libselinux-python is already installed"
          ]
     }

but it fails a bit later

    TASK [ipaserver : Install - Server installation test] **************************
    task path: /etc/ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipaserver/tasks/install.yml:46
    <ipa.devops.snapdevteam.com> ESTABLISH DOCKER CONNECTION FOR USER: root
    <ipa.devops.snapdevteam.com> EXEC ['/usr/bin/docker', b'exec', b'-i', 'ipa.devops.snapdevteam.com', '/bin/sh', '-c', "/bin/sh -c 'echo ~ && sleep 0'"]
    <ipa.devops.snapdevteam.com> EXEC ['/usr/bin/docker', b'exec', b'-i', 'ipa.devops.snapdevteam.com', '/bin/sh', '-c', '/bin/sh -c \'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1588972023.9272048-9674-257574601330026 && echo ansible-tmp-1588972023.9272048-9674-257574601330026="` echo /root/.ansible/tmp/ansible-tmp-1588972023.9272048-9674-257574601330026 `" ) && sleep 0\'']
    <ipa.devops.snapdevteam.com> EXEC ['/usr/bin/docker', b'exec', b'-i', 'ipa.devops.snapdevteam.com', '/bin/sh', '-c', "/bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1588972023.9272048-9674-257574601330026/ > /dev/null 2>&1 && sleep 0'"]
    The full traceback is:
    Traceback (most recent call last):
      File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
      File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
      File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
      File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 815, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
      File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 209, in _configure_module
    **become_kwargs)
      File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/module_common.py", line 1258, in modify_module
    environment=environment)
      File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/module_common.py", line 1095, in _find_module_utils
    py_module_cache, zf)
      File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/module_common.py", line 731, in recursive_finder
    [os.path.join(*py_module_name[:-idx])])
      File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/module_common.py", line 650, in __init__
    self.get_source()
      File "/home/bgiles/.molecule.venv/lib/python3.7/site-packages/ansible/executor/module_common.py", line 666, in get_source

Oddly I can reach the same point if I enable *only* installing dns or kra, then I reach the same point if I return to trying to install both. However when I run a second `molecule test` it fails with the same ValueError.

**Comment by t-woerner** [comment] 2020-09-03 12:42
This is an issue in ansible.
Closing as duplicate of #315

**Closed by t-woerner** 2020-09-03 12:42 UTC
