### ISSUE TITLE
freeipa.ansible_freeipa.ipauser ran with the same date shows changed in check mode

### ISSUE THREAD

**Issue by donescup** [freeipa/ansible-freeipa#869] opened 2022-07-27 21:51 UTC
Playbook fragment:

- name: Create user account in ipa
  freeipa.ansible_freeipa.ipauser: 
    ipaadmin_password: "{{ ipaadmin_pass }}"
    name: test_user1
    first: test
    last: user1
    uid: 99988
    gid: 1000
    homedir: /home/users/test_user1
    shell: /usr/bin/bash
    password: test_user1
    noprivate: True

- name: Setup password expiration for user account 
  freeipa.ansible_freeipa.ipauser: 
    ipaadmin_password: "{{ ipaadmin_pass }}"
    name: test_user1
    first: test
    last: user1
    passwordexpiration: "20220801000000"

- name: Setup2 password expiration for user account 
  freeipa.ansible_freeipa.ipauser: 
    ipaadmin_password: "{{ ipaadmin_pass }}"
    name: test_user1
    first: test
    last: user1
    passwordexpiration: "20220801000000"

---------------------

Output: when playbook run with check mode:

TASK [test : Create user account in ipa] ***************************************
changed: [infra01]
Wednesday 27 July 2022  21:33:18 +0000 (0:00:03.516)       0:00:13.026 ******** 

TASK [test : Setup password expiration for user account] ***********************
changed: [infra01]
Wednesday 27 July 2022  21:33:22 +0000 (0:00:03.283)       0:00:16.309 ******** 

TASK [test : Setup2 password expiration for user account] **********************
changed: [infra01]
Wednesday 27 July 2022  21:33:25 +0000 (0:00:03.380)       0:00:19.689 ******** 

--------------

Shouldn't task: Setup2 show "ok" instead of "changed"?

As a side note:
I have also seen the setup password expiration reporting "changed" even if the new date is the same as the old one when the playbook is run without check mode. But the behavior is intermittent, and right now I could not reproduce it in a simple playbook. This behavior shows up in the playbook being run twice.

**Comment by t-woerner** [comment] 2022-07-28 07:52
Yes, the task `Setup2 password expiration for user account` should not report a change.

**Comment by rclar802** [comment] 2022-09-26 20:53
@t-woerner Do we know if this bug has been fixed?

**Comment by t-woerner** [comment] 2022-09-27 11:28
No, it has not been fixed yet. But it is on the list for next fixes.

**Comment by t-woerner** [comment] 2022-09-30 13:13
`passwordexpiration` for users that are created with the server context (default for the plugins) is different compared to users that are created with the client context.
tests/user/test_user.yml is automatically executed in the server and also in the client context. Therefore this is the best place for the tests.

**Comment by rclar802** [comment] 2022-09-30 13:23
@t-woerner What is the best place for the tests at moment?

**Comment by dkarpele** [comment] 2022-09-30 15:44
Hi @donescup, I can't reproduce the issue you reported. Could you please recheck if it works for you on the latest version or if you see another issue. Thank you. 
```bash
  tasks:
  - name: User test_user1 present
    ipauser:
      ipaadmin_password: SomeADMINpassword
      first: test
      last: user
      name: test_user1

  - name: Setup password expiration for user account
    ipauser:
      ipaadmin_password: SomeADMINpassword
      name: test_user1
      passwordexpiration: "2022-12-01"

  - name: Setup2 password expiration for user account
    ipauser:
      ipaadmin_password: SomeADMINpassword
      name: test_user1
      passwordexpiration: "2022-12-01"

  - name: Setup new password expiration for user account
    ipauser:
      ipaadmin_password: SomeADMINpassword
      name: test_user1
      passwordexpiration: "3022-12-01"
```
```shell
$ ansible-playbook -v -i ../inventory/hosts.user user/test_user.yml 
PLAY [Test user] *******************************************************************************************************************

TASK [User test_user1 present] *****************************************************************************************************
changed: [10.0.188.64] => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": true, "user": {}}

TASK [Setup password expiration for user account] **********************************************************************************
changed: [10.0.188.64] => {"changed": true, "user": {}}

TASK [Setup2 password expiration for user account] *********************************************************************************
ok: [10.0.188.64] => {"changed": false, "user": {}}

TASK [Setup new password expiration for user account] ******************************************************************************
changed: [10.0.188.64] => {"changed": true, "user": {}}
...
```

**Comment by t-woerner** [comment] 2022-10-05 10:05
@donescup Which ansible-freeipa and IPA versions are you using?

**Comment by t-woerner** [comment] 2022-10-05 10:42
@rclar802 I only tried to remove my answer to your comment, but this removed the whole comment :-(

**Comment by larissaford** [comment] 2022-10-07 14:02
Hello, I'm on @donescup's team. I tried updating the ansible version but it still showed "changed:" instead of "ok:".

Here are what are hopefully the answers to your questions:

```
==>ipa --version
VERSION: 4.9.2, API_VERSION: 2.240

==>ansible-galaxy --version
ansible-galaxy [core 2.13.3]
  [...]
  python version = 3.8.6 (default, Jan 22 2021, 11:41:28) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.1.2
  libyaml = True

==>ansible --version
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  [...]
  python version = 3.8.6 (default, Jan 22 2021, 11:41:28) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.1.2
  libyaml = True
```

**Comment by jnm27** [comment] 2022-10-07 14:11
and freeipa 1.8.3

**Comment by rclar802** [comment] 2022-10-14 16:13
@dkarpele What latest version were you using, was it ipa-client-4.9.10?

**Comment by dkarpele** [comment] 2022-10-17 20:36
Thanks @larissaford, @jnm27, @rclar802 for providing the information. I found out that the described behaviour persists only in check mode and the version of the components doesn't matter. Without `--check` everything works for me. Also it doesn't matter if I run the playbook with or w/o `passwordexpiration` parametr. @larissaford, could you confirm that it reproduces only in check mode?

**Comment by rclar802** [comment] 2022-10-18 21:24
Hi @dkarpele , 

I tried running without check mode; however, there was no difference. It seems with each run there is a different changed outcome per task. What is the latest version you are running by the way?

TASK [Create user account in ipa] **********************************************
changed: [sup01]
Tuesday 18 October 2022  21:18:03 +0000 (0:00:00.067)       0:00:05.918 *******

TASK [Setup password expiration for user account] ******************************
changed: [sup01]
Tuesday 18 October 2022  21:18:09 +0000 (0:00:02.618)       0:00:11.874 *******

TASK [Setup2 password expiration for user account] *****************************
changed: [sup01]
Tuesday 18 October 2022  21:18:14 +0000 (0:00:04.550)       0:00:16.981 *******

TASK [Setup new password expiration for user account] **************************
changed: [sup01]

**Comment by dkarpele** [comment] 2022-10-19 08:29
Hi @rclar802 , I'm using 
```
[dkarpele@fedora ansible_freeipa]$ ansible --version | grep core
ansible [core 2.13.3]
[dkarpele@fedora ansible_freeipa]$ ansible-galaxy --version | grep core
ansible-galaxy [core 2.13.3]
[dkarpele@fedora ansible_freeipa]$ ansible-galaxy collection list freeipa.ansible_freeipa | grep freeipa.ansible_freeipa
freeipa.ansible_freeipa 1.8.3
```
and I checked with `ipa-4.9.2` and `ipa-4.9.10`.

**Comment by rclar802** [comment] 2022-10-19 17:08
Hi @dkarpele, 

For my last reply I should say that I ran with "our" changes without checkmode enabled and we still saw changes made. I think it comes down to the variable "password". Using below code example could you try running with password variable set. 

`- name: Test playbook
  hosts: "{{ target_host }}"
  gather_facts: False
  tasks:
  - name: Create user account in ipa
    freeipa.ansible_freeipa.ipauser:
      ipaadmin_password: "{{ ipaadmin_pass }}"
      name: test_user1
      first: test
      last: user1
      uid: 99988
      gid: 1000
      homedir: /home/users/test_user1
      shell: /usr/bin/bash
      **password: test_user1**
      noprivate: True
  - name: Setup password expiration for user account
    freeipa.ansible_freeipa.ipauser:
      ipaadmin_password: "{{ ipaadmin_pass }}"
      name: test_user1
      first: test
      last: user1
      passwordexpiration: "2022-12-01"
  - name: Setup2 password expiration for user account
    freeipa.ansible_freeipa.ipauser:
      ipaadmin_password: "{{ ipaadmin_pass }}"
      name: test_user1
      first: test
      last: user1
      passwordexpiration: "2022-12-01"
  - name: Setup new password expiration for user account
    freeipa.ansible_freeipa.ipauser:
      ipaadmin_password: "{{ ipaadmin_pass }}"
      name: test_user1
      first: test
      last: user1
      passwordexpiration: "3022-12-01"`

**Comment by t-woerner** [comment] 2022-10-19 18:28
@rclar802  Your playbook is as is working for me as expected. The tasks 1, 2 and 4 are reporting `changed:true`, the 3rd is reporting `changed:false`. I tested it with different IPA and ansible-freeipa versions.

I also executed this playbook 100 times in a sequence and made sure that tasks are failing if they return an unexpected changed value. The test ran without a failure with different IPA versions.

Only if `password: test_user1` is added to the 3rd task, then this task will also return changed. But this is expected and controlled with the `update_password` parameter.

**Comment by rclar802** [comment] 2022-11-14 19:35
Reran this same task and now I'm not seeing this issue anymore. Closing this ticket.

`PLAY [Test playbook] ***************************************************************************************
Monday 14 November 2022  19:29:36 +0000 (0:00:00.203)       0:00:00.203 *******

TASK [Create user account in ipa] **************************************************************************
changed: [sup01]
Monday 14 November 2022  19:29:40 +0000 (0:00:04.339)       0:00:04.542 *******

TASK [Setup password expiration for user account] **********************************************************
changed: [sup01]
Monday 14 November 2022  19:29:44 +0000 (0:00:03.459)       0:00:08.002 *******

TASK [Setup2 password expiration for user account] *********************************************************
ok: [sup01]
[sup01] TASK: Setup2 password expiration for user account (debug)> c
Monday 14 November 2022  19:29:49 +0000 (0:00:05.453)       0:00:13.455 *******

TASK [Setup new password expiration for user account] ******************************************************
changed: [sup01]

PLAY RECAP *************************************************************************************************
sup01                      : ok=4    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
`

**Comment by rjeffman** [comment] 2022-12-13 18:39
As it seems it is not an issue anymore, I'm closing this issue.

If you find that the solution is not sufficient, please, either reopen this issue or create a new one.

**Closed by rjeffman** 2022-12-13 18:39 UTC
Labels: bug
